// Source-backed analytics. All dynamic text is escaped; charts also have tabular detail.
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = v => v == null ? 'Unavailable' : Number(v).toLocaleString();
const compact = v => v == null ? 'Unavailable' : Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(v);
const money = v => v == null ? 'Unavailable' : new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:v>0&&v<.01?6:2}).format(v);
const time = v => v ? new Date(/^\d{4}-\d{2}-\d{2}T\d{2}$/.test(v)?v+':00:00Z':v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}) : 'Not recorded';
const url = (sid,extra={}) => '#sessions?'+new URLSearchParams({sid,...extra});
const panel = (title,subtitle,body,action='') => `<section class="panel analytics-panel"><div class="panel-head"><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div>${action}</div>${body}</section>`;
const stat = (title,value,note,cls='') => `<div class="analysis-stat ${cls}"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`;
const note = text => `<p class="analysis-note">${esc(text)}</p>`;
const none = text => `<div class="analysis-empty">${esc(text)}</div>`;
const tokenFields = [['uncached_input_tokens','Fresh input','fresh'],['cached_input_tokens','Cache read','cached'],['cache_write_input_tokens','Cache write','write'],['output_tokens','Output','output']];
const categoryNames = {uncached_input:'Fresh input',cached_input:'Cache read',cache_write_5m:'Cache write, 5 minutes',cache_write_1h:'Cache write, 1 hour',cache_write:'Cache write',output:'Output'};
let current=null, ledgerState={q:'',model:'',kind:'',sort:'newest',page:0};

function table(headers,rows,cls='') {
  return `<div class="table-wrap"><table class="data-table analysis-table ${cls}"><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
}
function sourceLabel(s) {return s?`${s.kind||'transcript'}${s.line?' / line '+s.line:''}`:'Source unavailable';}
function sessionLink(a,view,extra={}) {return url(a.session.sid,{view,...(a.session.child_id?{child:a.session.child_id}:{}),...extra});}
function breakdown(a) {
  const sums={};
  for(const r of a.ledger||[])for(const [key,value] of Object.entries(r.cost?.breakdown_usd||{}))if(typeof value==='number')sums[key]=(sums[key]||0)+value;
  return sums;
}
function tokenComposition(tokens={}) {
  const complete=tokenFields.every(([k])=>tokens[k]!=null),total=complete?tokens.total_tokens:0;
  const unknown=complete?'':note('Some token categories are missing. Composition percentages are unavailable; measured input and output remain in the totals.');
  return `${unknown}<div class="token-composition"><div class="token-track" role="img" aria-label="Token composition: ${esc(tokenFields.map(([k,l])=>l+' '+number(tokens[k])).join(', '))}">${tokenFields.map(([k,l,c])=>`<span class="${c}" style="width:${total?100*(tokens[k]||0)/total:0}%" title="${esc(l+': '+number(tokens[k]))}"></span>`).join('')}</div><div class="token-legend">${tokenFields.map(([k,l,c])=>`<div><span><i class="swatch ${c}"></i>${l}</span><strong title="${esc(number(tokens[k]))}">${compact(tokens[k])}</strong><small>${tokens[k]!=null&&total?(100*tokens[k]/total).toFixed(1)+'%':'Not measured'}</small></div>`).join('')}</div></div>`;
}
function lineChart(points,{value='tokens',label='Context tokens',capacity=null,cost=false,link=null}={}) {
  const valid=points.filter(p=>Number.isFinite(p[value]));
  if(!valid.length)return none('No '+label.toLowerCase()+' samples were captured.');
  const w=800,h=210,left=56,right=12,top=18,bottom=36;
  const max=Math.max(1,capacity||0,...valid.map(p=>p[value]));
  const ts=valid.map(p=>Date.parse(p.ts||p.hour)), timed=ts.every(Number.isFinite)&&Math.max(...ts)>Math.min(...ts);
  const minTs=Math.min(...ts),span=Math.max(...ts)-minTs;
  const x=(p,i)=>left+(timed?(ts[i]-minTs)/span:i/Math.max(1,valid.length-1))*(w-left-right);
  const y=n=>top+(1-n/max)*(h-top-bottom);
  const line=valid.map((p,i)=>`${x(p,i).toFixed(2)},${y(p[value]).toFixed(2)}`).join(' ');
  const show=n=>cost?money(n):compact(n);
  const nodes=valid.map((p,i)=>{const dot=`<circle cx="${x(p,i)}" cy="${y(p[value])}" r="${valid.length>300?2:3.5}" tabindex="0"><title>${esc(time(p.ts||p.hour)+': '+show(p[value]))}</title></circle>`;return link?`<a href="${esc(link(p))}" aria-label="${esc(time(p.ts||p.hour)+': '+show(p[value]))}">${dot}</a>`:dot;}).join('');
  return `<div class="analysis-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)} over captured time"><title>${esc(label)} over captured time</title>${[0,.5,1].map(r=>`<line class="chart-grid" x1="${left}" x2="${w-right}" y1="${y(max*r)}" y2="${y(max*r)}"/><text x="${left-8}" y="${y(max*r)+4}" text-anchor="end">${esc(show(max*r))}</text>`).join('')}${capacity?`<line class="chart-capacity" x1="${left}" x2="${w-right}" y1="${y(capacity)}" y2="${y(capacity)}"/>`:''}<polygon class="chart-area" points="${left},${h-bottom} ${line} ${x(valid.at(-1),valid.length-1)},${h-bottom}"/><polyline class="chart-line" points="${line}"/>${nodes}<text x="${left}" y="${h-8}">${esc(time(valid[0].ts||valid[0].hour))}</text><text x="${w-right}" y="${h-8}" text-anchor="end">${esc(time(valid.at(-1).ts||valid.at(-1).hour))}</text></svg></div>`;
}
function bars(items,value,label,format=number) {
  const max=Math.max(1,...items.map(r=>r[value]||0));
  return items.length?`<div class="analysis-bars">${items.map(r=>`<div class="analysis-bar"><span title="${esc(r[label])}">${esc(r[label])}</span><div><i style="width:${100*(r[value]||0)/max}%"></i></div><strong>${esc(format(r[value]))}</strong></div>`).join('')}</div>`:none('No records captured in this scope.');
}
function pricingCoverage(a) {
  const s=a.summary||{}, count=s.costed_responses||0;
  return `${number(count)} of ${number(s.responses)} responses priced. ${a.coverage.total_is_exact?'Available source fully scanned.':'Partial source scan; totals describe captured records only.'}`;
}
function contextSummary(a) {
  const c=a.context||{};
  return `<div class="context-meter"><div><strong>${c.current_percent==null?compact(c.current_tokens):Number(c.current_percent).toFixed(1)+'%'}</strong><span>${c.current_percent==null?'Latest measured input':'of the recorded context limit'}</span></div><div class="context-track"><i style="width:${Math.min(100,Math.max(0,c.current_percent||0))}%"></i></div><div class="context-labels"><span>${number(c.current_tokens)} input tokens</span><span>${c.capacity_tokens==null?'Limit not captured':number(c.capacity_tokens)+' limit'}</span></div></div>`;
}
function overview(a) {
  const s=a.summary,c=a.context,client=a.cost?.reported_usd;
  const firstResponse=(a.ledger||[])[0];
  return `<div class="analysis-stats">${stat('Estimated API cost',money(s.estimated_cost_usd),`${number(s.costed_responses)} responses priced`,'cost')}${stat('Tokens processed',compact(s.tokens?.total_tokens),'Input plus output; cache included once')}${stat('Model responses',number(s.responses),`${number(s.tool_calls)} tool calls captured`)}${stat('Latest context',c.current_percent==null?compact(c.current_tokens):c.current_percent.toFixed(1)+'%',c.capacity_tokens?number(c.capacity_tokens)+' token limit':'Recorded input; limit unavailable')}</div>
  <div class="analysis-two">${panel('Where the tokens go','Cumulative usage across model responses',tokenComposition(s.tokens||{})+note('Cache reads count each time context is reused. This total is not the size of the context window.'))}${panel('Cost at a glance','USD, with the source of each amount shown',`<div class="cost-comparison"><div><span>Calculated from published rates</span><strong>${money(s.estimated_cost_usd)}</strong></div><div><span>Client cost snapshot</span><strong>${money(client)}</strong></div><div><span>Average per priced response</span><strong>${money(s.average_cost_usd)}</strong></div></div>${note((a.cost?.reported_usd!=null?'The client snapshot can include child agents and other activity. It has a different scope from the main conversation estimate.':null)||'No client cost snapshot is captured. Subscription payments and invoices are not inferred.')}`)}</div>
  ${panel('Context over time','Input size at each model response. Select a point to inspect its transcript.',lineChart(c.timeline||[],{capacity:c.capacity_tokens,link:p=>sessionLink(a,'conversation',{around:p.source?.line||firstResponse?.source?.line||1})})+note('The line tracks observed input, including cached context. It does not add output or lifetime token totals to the current window.'))}
  <div class="analysis-two">${panel('Activity by hour','Model responses, grouped by captured time',bars((a.hourly||[]).map(x=>({...x,label:time(x.hour)})),'responses','label'))}${panel('Most used tools','Captured calls in the selected conversation',bars([...(a.tools||[])].sort((x,y)=>y.count-x.count).slice(0,8),'count','name'))}</div>
  ${note(pricingCoverage(a))}`;
}
// Where a rate card came from. A built-in card (or an older payload without `origin`) keeps the
// original wording; a card an agent recorded from the official price page names its evidence.
function cardOrigin(r) {
  if(r.origin!=='recorded')return `<p>Verified ${esc(r.verified_at)}. ${esc(r.basis)}.</p>`;
  const l=r.label||{},row=l.row==null?'':typeof l.row==='string'?l.row:JSON.stringify(l.row);
  return `<p>Recorded by an agent from the official price page on ${esc(r.verified_at||l.recorded_at||'an unrecorded date')}${l.method?` (method: ${esc(l.method)})`:''}.${r.basis?' '+esc(r.basis)+'.':''}</p>${l.source_sha256||row?`<dl class="detail-grid">${l.source_sha256?`<dt>Price page SHA-256</dt><dd class="mono" title="First 12 characters">${esc(String(l.source_sha256).slice(0,12))}</dd>`:''}${row?`<dt>Price row</dt><dd class="mono">${esc(row)}</dd>`:''}</dl>`:''}`;
}
function costView(a) {
  const costs=breakdown(a),s=a.summary,priced=(a.ledger||[]).filter(r=>r.cost?.total_usd!=null);
  const ratecards=[...new Map(priced.map(r=>[JSON.stringify(r.cost.rate_card),r.cost.rate_card])).values()].filter(Boolean);
  return `<div class="analysis-stats">${stat('Estimated API cost',money(s.estimated_cost_usd),'Published rate-card calculation','cost')}${stat('Client cost snapshot',money(a.cost?.reported_usd),'As recorded by the client; not an invoice')}${stat('Average / response',money(s.average_cost_usd),'Only responses with a known price')}${stat('Pricing coverage',`${number(s.costed_responses)} / ${number(s.responses)}`,'Priced responses / captured responses')}</div>
  <div class="analysis-two">${panel('Token usage','Reasoning tokens are a subset of output, not extra tokens',tokenComposition(s.tokens||{})+table(['Measured category','Tokens'],[['Input, including cache',s.tokens?.input_tokens],['Cache written for 5 minutes',s.tokens?.cache_creation_5m_tokens],['Cache written for 1 hour',s.tokens?.cache_creation_1h_tokens],['Reasoning output (within output)',s.tokens?.reasoning_output_tokens],['Total input + output',s.tokens?.total_tokens]].map(([label,n])=>`<tr><td>${label}</td><td>${number(n)}</td></tr>`)))}${panel('Estimated cost by category',a.ledger_truncated?'Subtotal of displayed responses; ledger is capped':'Sum of priced model responses',bars(Object.entries(costs).map(([key,value])=>({name:categoryNames[key]||key,value})),'value','name',money)+note('Tool attribution below divides a response estimate across its tool calls. It is not a separate fee charged by a tool.'))}</div>
  ${panel('Cost per response','Select a point to see the visible conversation around that response.',lineChart(priced.map(r=>({...r,value:r.cost.total_usd})),{value:'value',label:'Estimated cost per response',cost:true,link:r=>sessionLink(a,'conversation',{around:r.source?.line||1})}))}
  ${a.cost?.imported_reported_usd!=null?panel('Imported reported cost','Explicitly supplied usage records; separate from the transcript estimate',`<div class="cost-comparison"><div><span>${a.cost.imported_partial?'Captured subtotal':'Reported total'}</span><strong>${money(a.cost.imported_reported_usd)}</strong></div></div>${note(a.cost.imported_scope)}<details class="analysis-method"><summary>Import evidence</summary><pre>${esc(JSON.stringify(a.cost.imported_sources,null,2))}</pre></details>`):''}
  ${panel('Models used','Totals for the selected conversation',table(['Model','Responses','Input','Output','Estimated cost'],(a.models||[]).map(m=>`<tr><td class="mono">${esc(m.model)}</td><td>${number(m.responses)}</td><td>${compact(m.tokens?.input_tokens)}</td><td>${compact(m.tokens?.output_tokens)}</td><td>${money(m.estimated_cost_usd)}<small class="row-sub">${number(m.costed_responses)} priced</small></td></tr>`)))}
  ${panel('Pricing sources & assumptions','Current API list prices are estimates, not a historical bill',ratecards.length?`<div class="ratecards">${ratecards.map(r=>`<details><summary>${esc(r.model)} <span>${esc(r.context_tier)} context / ${esc(r.service_tier||'standard')} service${r.origin==='recorded'?' / recorded by an agent':''}</span></summary>${cardOrigin(r)}<div class="link-row">${[...new Set([r.source_url,...(r.source_urls||[])])].filter(u=>/^https:\/\//.test(u||'')).map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">Official pricing source</a>`).join('')}</div>${table(['Category','USD / 1 million tokens'],Object.entries(r.rates_per_million||{}).map(([k,v])=>`<tr><td>${esc(categoryNames[k]||k)}</td><td>${money(v)}</td></tr>`))}<p>Context multiplier: input ${esc(r.input_multiplier)}x, output ${esc(r.output_multiplier)}x. Service multiplier: ${esc(r.service_multiplier??1)}x.</p></details>`).join('')}</div>`:none('No verified rate card matches the captured responses. Token measurements remain available.'))}
  ${ledgerShell(a)}${note(pricingCoverage(a))}`;
}
function contextView(a) {
  const c=a.context||{},compactions=Array.isArray(c.compactions)?c.compactions:[];
  return `<div class="analysis-stats">${stat('Latest input',compact(c.current_tokens),'Includes cached context')}${stat('Peak input',compact(c.peak_tokens),'Largest observed request')}${stat('Context capacity',compact(c.capacity_tokens),'Limit recorded in the transcript')}${stat('Compactions',number(Array.isArray(c.compactions)?c.compactions.length:c.compactions),'Recorded context reduction events')}</div>
  ${panel('Context window','Measured input against the recorded capacity',contextSummary(a)+lineChart(c.timeline||[],{capacity:c.capacity_tokens,link:p=>sessionLink(a,'conversation',{around:p.source?.line||1})})+note('The capacity is shown only when recorded. A large lifetime token total does not mean the context window is full. A drop in the line can follow compaction, a shorter request, or a changed model; drops alone are not counted as compactions.'))}
  ${panel('Compaction history','Only explicit compaction records are counted',compactions.length?table(['Time','Event','Source'],compactions.map(c=>`<tr><td>${time(c.ts)}</td><td>${esc(c.type||'Context compacted')}</td><td>${esc(sourceLabel(c.source))}</td></tr>`)):none('No explicit compaction records were captured.'))}
  ${panel('Context samples','Latest 100 samples. Full captured measurements are included in the JSON download.',table(['Time','Input tokens','Recorded limit','Use','Transcript'],(c.timeline||[]).slice(-100).reverse().map(p=>`<tr><td>${time(p.ts)}</td><td>${number(p.tokens)}</td><td>${number(p.capacity)}</td><td>${p.percent==null?'Unavailable':p.percent.toFixed(1)+'%'}</td><td><a href="${esc(sessionLink(a,'conversation',{around:p.source?.line||1}))}">Open</a></td></tr>`)))} `;
}
function actionsView(a) {
  const hooks=a.hooks||{},nested=a.nested_actions||{};
  return `<div class="analysis-stats">${stat('Tool calls',number(a.summary.tool_calls),'Calls captured in this conversation')}${stat('Tool types',number((a.tools||[]).length),'Distinct action names')}${stat('Hook records',number(hooks.total),'Recorded executions and context injections')}${stat('Hook types',number((hooks.by_type||[]).length),'Events observed in the source')}</div>
  ${panel('Actions & allocated cost','An equal share of each priced response is assigned to its tool calls',table(['Tool','Calls','Tool error flags','Allocated estimate','Estimate / priced call'],(a.tools||[]).map(t=>`<tr><td class="mono">${esc(t.name)}</td><td>${number(t.count)}</td><td>${number(t.errors)}</td><td>${money(t.estimated_allocated_cost_usd)}</td><td>${money(t.estimated_allocated_cost_usd==null||!t.costed_calls?null:t.estimated_allocated_cost_usd/t.costed_calls)}</td></tr>`))+note('These estimates describe model usage around an action. They do not measure the tool\'s intrinsic price, runtime cost, or a separate provider charge. Responses without tools remain in the session total. The per-call average uses priced calls only. Tool error flags do not count failures inside nested shell commands.'))}
  <div class="analysis-two">${panel('Hooks by event','Context injections and execution records stay distinguishable',bars(hooks.by_type||[],'count','type'))}${panel('How to read this activity','A captured event is evidence of activity, not task completion',`<div class="panel-body"><p>Tool calls show what the agent attempted and any captured error result. Hooks show lifecycle actions and context supplied to the agent.</p><p class="analysis-note">Codex uses explicit lifecycle commands in this project. Claude hook records are shown where its transcript captured them. An absent hook record is not proof that no hook ran.</p><a href="#activity?session=${encodeURIComponent(a.session.sid)}">Open the project activity record</a></div>`)}</div>
  ${panel('Commands and nested actions','Statuses captured inside the outer tool calls',nested.items?.length?`<div class="analysis-note">${number(nested.total)} action records / ${number(nested.failed)} recorded failures. ${esc(nested.basis||'Only captured status metadata is counted.')}</div>`+table(['Time','Action','Status','Exit code','Transcript'],nested.items.slice(-100).reverse().map(n=>`<tr><td>${time(n.ts)}</td><td>${esc(n.type)}</td><td>${esc(n.status)}</td><td>${n.exit_code==null?'Not recorded':number(n.exit_code)}</td><td><a href="${esc(sessionLink(a,'conversation',{around:n.source?.line||1}))}">Open</a></td></tr>`)):none('No separate nested-action status records are available for this conversation.'))}
  ${panel('Hook timeline','Captured metadata; hook instructions and secret inputs are excluded',hooks.events?.length?table(['Time','Hook event','Record','Status','Source'],hooks.events.slice(-200).reverse().map(h=>`<tr><td>${time(h.ts)}</td><td>${esc(h.event||h.name||h.type)}</td><td>${esc(h.type.replaceAll('_',' '))}</td><td>${esc(h.status||'captured')}</td><td class="mono">${esc(sourceLabel(h.source))}</td></tr>`)):none('No hook records are captured in this conversation.'))}`;
}
function ledgerShell(a) {
  return panel('Response ledger','Usage and estimated cost for each model response; expand a row for evidence',`<div class="ledger-toolbar"><input type="search" data-analysis-filter="q" placeholder="Find a response or tool..." aria-label="Search response ledger"><select data-analysis-filter="model" aria-label="Filter response model"><option value="">All models</option>${(a.models||[]).map(m=>`<option>${esc(m.model)}</option>`).join('')}</select><select data-analysis-filter="kind" aria-label="Filter response actions"><option value="">All responses</option><option value="tools">With tools</option><option value="text">Without tools</option><option value="unpriced">Missing price</option></select><select data-analysis-filter="sort" aria-label="Sort response ledger"><option value="newest">Latest first</option><option value="oldest">Oldest first</option><option value="cost">Highest cost</option><option value="context">Largest context</option></select></div><div id="response-ledger">${ledgerRows(a)}</div>`,`<button class="button" data-analysis-action="csv">Export CSV</button>`);
}
function ledgerRows(a) {
  const q=ledgerState.q.toLowerCase();
  const rows=(a.ledger||[]).filter(r=>(!q||JSON.stringify([r.excerpt,r.tools,r.model,r.id]).toLowerCase().includes(q))&&(!ledgerState.model||r.model===ledgerState.model)&&(!ledgerState.kind||(ledgerState.kind==='tools'?r.tools?.length:ledgerState.kind==='text'?!r.tools?.length:r.cost?.total_usd==null)));
  rows.sort((a,b)=>ledgerState.sort==='cost'?(b.cost?.total_usd??-1)-(a.cost?.total_usd??-1):ledgerState.sort==='context'?(b.context_tokens??-1)-(a.context_tokens??-1):ledgerState.sort==='oldest'?String(a.ts).localeCompare(String(b.ts)):String(b.ts).localeCompare(String(a.ts)));
  const limit=30,pages=Math.max(1,Math.ceil(rows.length/limit));ledgerState.page=Math.min(ledgerState.page,pages-1);
  const visible=rows.slice(ledgerState.page*limit,(ledgerState.page+1)*limit);
  return (visible.length?table(['Response / actions','Time','Input','Output','Estimated cost',''],visible.map(r=>`<tr><td><button class="row-title" data-analysis-response="${esc(r.id)}">${esc((r.excerpt||r.tools?.map(t=>t.name).join(', ')||'Model response').slice(0,110))}</button><small class="row-sub mono">${esc(r.model)}${r.tools?.length?' / '+r.tools.length+' tools':''}</small></td><td>${time(r.ts)}</td><td>${compact(r.usage?.input_tokens)}</td><td>${compact(r.usage?.output_tokens)}</td><td>${money(r.cost?.total_usd)}</td><td><button class="text-link" data-analysis-response="${esc(r.id)}">Inspect</button></td></tr>`)):none('No responses match these filters.'))+`<div class="pagination"><button class="button" data-analysis-action="prev" ${ledgerState.page===0?'disabled':''}>Previous</button><span>${number(rows.length)} responses / page ${ledgerState.page+1} of ${pages}</span><button class="button" data-analysis-action="next" ${ledgerState.page>=pages-1?'disabled':''}>Next</button></div>${a.ledger_truncated?note('The response table is capped. Aggregate totals cover the source scan; this table and CSV contain only the displayed ledger capture.'):''}`;
}
// keepLedger: a live refresh of the same view keeps the reader's ledger search, filters and page.
export function renderAnalytics(a,view='analysis',{keepLedger=false}={}) {
  current=a;if(!keepLedger)ledgerState={q:'',model:'',kind:'',sort:'newest',page:0};
  return `<div id="analytics-content" class="analytics-content"><div class="analysis-scope"><span><i></i>${a.session.child_id?'Child conversation':'Main conversation'} only</span><span>${esc({'claude-response-ids':'Unique Claude responses','native-response-records':'Recorded Codex responses','snapshot-last-usage':'Recorded usage snapshots'}[a.coverage.usage_method]||'Transcript measurements')} / ${esc(a.coverage.state)}</span><button class="text-link" data-analysis-action="json">Download captured data</button></div>${!a.coverage.usage_total_is_exact?note('Usage coverage is incomplete. Totals describe the measured responses only; missing usage is not treated as zero.'):''}${({analysis:overview,cost:costView,context:contextView,actions:actionsView}[view]||overview)(a)}<details class="analysis-method"><summary>Capture coverage and calculation method</summary><p>${esc(a.coverage.reason)}</p><p>${esc(pricingCoverage(a))} Child conversations are analyzed separately. Visible text, tool names and usage metadata are retained; private reasoning is excluded.</p><pre>${esc(JSON.stringify(a.coverage,null,2))}</pre></details></div>`;
}
// Responses the index could not price. A model without a rate card names the server's own fix
// command (an agent records the card from the official price page); older payloads carry neither field.
function unpricedNotes(tot) {
  const models=Array.isArray(tot.unpriced_models)?tot.unpriced_models:[],other=Number(tot.unpriced_other)||0;
  return models.map(m=>`<p class="inline-warning analysis-unpriced">${esc(m.model)}: ${number(m.responses)} responses in ${number(m.sessions)} sessions have no rate card. An agent records one from the official price page${m.fix?`: <code>${esc(m.fix)}</code>`:'.'}</p>`).join('')+(other>0?`<p class="inline-warning analysis-unpriced">${number(other)} responses lack usable usage or cache-duration data</p>`:'');
}
export function analyticsIndex(data) {
  const rows=data.sessions||[],tot=data.totals||{};
  return `<div class="analysis-stats">${stat('Sessions analyzed',number(rows.length),`${number(tot.measured_sessions)} have usage / ${number(tot.partial_sessions)} partial captures`)}${stat('Estimated API cost',money(tot.estimated_cost_usd),`${number(tot.costed_responses)} of ${number(tot.responses)} responses priced`,'cost')}${stat('Tokens processed',compact(tot.total_tokens),'Measured main conversations; cache counted once')}${stat('Model responses',number(tot.responses),'Unique responses from source records')}</div>
  ${unpricedNotes(tot)}${panel('Usage & cost across sessions','Select a session for costs, context, actions and its conversation',table(['Session','Responses','Input / output','Estimated API cost','Client cost snapshot','Capture'],rows.map(s=>`<tr data-key="${esc(s.sid)}"><td><a class="row-title" href="${esc(url(s.sid))}">${esc(s.title||s.sid)}</a><small class="row-sub">${time(s.first)} / ${esc(s.operator||'agent')}</small></td><td>${number(s.summary?.responses)}</td><td>${compact(s.summary?.tokens?.input_tokens)} / ${compact(s.summary?.tokens?.output_tokens)}</td><td>${money(s.summary?.estimated_cost_usd)}<small class="row-sub">${number(s.summary?.costed_responses)} priced</small></td><td>${money(s.cost?.reported_usd)}<small class="row-sub">${s.cost?.reported_usd!=null?'Client scope; may include children':''}</small></td><td><span class="badge neutral">${esc(s.coverage?.state||'unavailable')}</span>${s.error?`<small class="row-sub">${esc(s.error)}</small>`:''}</td></tr>`)))}
  ${note('Estimated API cost uses published rates for captured responses. Totals above exclude child conversations, which are available inside each session. Client snapshots retain their own scope and are not added together. These figures do not establish a subscription bill.')}`;
}
export function renderCrew(data) {
  const t=data.totals,rows=data.conversations;
  return `<div class="analytics-content"><div class="analysis-scope"><span><i></i>Main conversation + discovered child agents</span></div><div class="analysis-stats">${stat('Combined estimated cost',money(t.estimated_cost_usd),data.complete?'All discovered responses priced':'Subtotal; some usage or pricing is missing','cost')}${stat('Model responses',number(t.responses),`${number(t.costed_responses)} responses priced`)}${stat('Tokens processed',compact(t.total_tokens),'Across captured main and child records')}${stat('Conversations',number(rows.length),`${rows.length-1} discovered children + main`)}</div>${panel('Agent crew','Each row has its own transcript, measurements and scope',table(['Conversation','Responses','Input / output','Estimated cost','Capture'],rows.map(r=>`<tr><td><a class="row-title" href="${esc(url(data.sid,{...(r.id?{child:r.id}:{}),view:'analysis'}))}">${esc(r.title)}</a><small class="row-sub">${r.id?'Child agent':'Parent session'}</small></td><td>${number(r.summary.responses)}</td><td>${compact(r.summary.tokens?.input_tokens)} / ${compact(r.summary.tokens?.output_tokens)}</td><td>${money(r.summary.estimated_cost_usd)}<small class="row-sub">${number(r.summary.costed_responses)} priced</small></td><td>${esc(r.coverage.state)}</td></tr>`)))}${note(data.scope)}${!data.complete?note('This is a captured subtotal. Missing child files, missing usage, unknown rates or source limits can prevent a complete total.'):''}</div>`;
}
function download(text,name,type='text/plain') {const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function inspectResponse(r) {
  const a=current,d=document.querySelector('#inspector');
  document.querySelector('#inspector-label').textContent='RESPONSE EVIDENCE';
  document.querySelector('#inspector-content').innerHTML=`<h2 class="detail-title" id="inspector-title">${esc(r.excerpt||'Model response')}</h2><div class="analysis-stats response-stats">${stat('Estimated cost',money(r.cost?.total_usd),r.cost?.status||'Unavailable')}${stat('Input tokens',number(r.usage?.input_tokens),'Includes cache')}${stat('Output tokens',number(r.usage?.output_tokens),'Includes reasoning usage')}</div><dl class="detail-grid"><dt>Model</dt><dd>${esc(r.model)}</dd><dt>Time</dt><dd>${time(r.ts)}</dd><dt>Source</dt><dd>${esc(sourceLabel(r.source))}</dd><dt>Response ID</dt><dd class="mono">${esc(r.id)}</dd><dt>Association</dt><dd>${esc(r.association||'Recorded response identity')}</dd></dl>${r.source?.line?`<a class="button primary" href="${esc(sessionLink(a,'conversation',{around:r.source.line}))}">Open in conversation</a>`:''}<section class="detail-section"><h3>Token measurements</h3>${table(['Category','Tokens'],Object.entries(r.usage||{}).filter(([k])=>k.endsWith('_tokens')).map(([k,v])=>`<tr><td>${esc(k.replaceAll('_',' '))}</td><td>${number(v)}</td></tr>`))}</section><section class="detail-section"><h3>Actions in this response</h3>${r.tools?.length?r.tools.map(t=>`<p class="mono">${esc(t.name)} / ${esc(t.status||'captured')}</p>`).join(''):note('No tool calls associated with this response.')}</section><section class="detail-section"><h3>Cost calculation</h3>${r.cost?.reason?note(r.cost.reason):''}${table(['Category','Estimated USD'],Object.entries(r.cost?.breakdown_usd||{}).map(([k,v])=>`<tr><td>${esc(categoryNames[k]||k)}</td><td>${money(v)}</td></tr>`))}${(r.cost?.assumptions||[]).map(note).join('')}<details><summary>Rate card and provenance</summary><pre class="raw-data">${esc(JSON.stringify(r.cost?.rate_card||{},null,2))}</pre></details></section>`;
  d.classList.remove('reader');d.showModal();
}
document.addEventListener('input',e=>{if(e.target.matches('[data-analysis-filter]')){ledgerState[e.target.dataset.analysisFilter]=e.target.value;ledgerState.page=0;document.querySelector('#response-ledger').innerHTML=ledgerRows(current);}});
document.addEventListener('change',e=>{if(e.target.matches('select[data-analysis-filter]')){ledgerState[e.target.dataset.analysisFilter]=e.target.value;ledgerState.page=0;document.querySelector('#response-ledger').innerHTML=ledgerRows(current);}});
document.addEventListener('click',e=>{
  const target=e.target.closest('[data-analysis-action],[data-analysis-response]');if(!target||!current)return;
  if(target.dataset.analysisResponse){const r=current.ledger.find(r=>r.id===target.dataset.analysisResponse);if(r)inspectResponse(r);return;}
  const action=target.dataset.analysisAction;
  if(action==='prev'||action==='next'){ledgerState.page+=action==='next'?1:-1;document.querySelector('#response-ledger').innerHTML=ledgerRows(current);return;}
  if(action==='json')download(JSON.stringify(current,null,2),current.session.sid+'-analytics.json','application/json');
  if(action==='csv'){
    const quote=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
    const rows=[['response_id','timestamp','model','input_tokens','cached_input_tokens','output_tokens','estimated_usd','source_line','visible_excerpt'],...current.ledger.map(r=>[r.id,r.ts,r.model,r.usage?.input_tokens,r.usage?.cached_input_tokens,r.usage?.output_tokens,r.cost?.total_usd,r.source?.line,r.excerpt])];
    download(rows.map(r=>r.map(quote).join(',')).join('\r\n'),current.session.sid+'-responses.csv','text/csv');
  }
});
