// Visual projections of recorded work. A chart never supplies a missing verdict.
import {icon} from './icons.js';
import {systemPanel,startSystem} from './system.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number(v||0).toLocaleString();
const date=v=>{if(!v)return 'Not recorded';const d=new Date(typeof v==='number'?v*1000:v);return Number.isNaN(+d)?'Not recorded':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});};
const age=v=>{if(!v)return 'No timestamp';const ms=Date.now()-new Date(typeof v==='number'?v*1000:v);return !Number.isFinite(ms)?'No timestamp':ms<60000?'just now':ms<3600000?Math.floor(ms/60000)+'m ago':ms<86400000?Math.floor(ms/3600000)+'h ago':Math.floor(ms/86400000)+'d ago';};
const short=(s,len=130)=>String(s||'').length>len?String(s).slice(0,len)+'...':String(s||'');
const href=(route,params={})=>'#'+route+(Object.keys(params).length?'?'+new URLSearchParams(params):'');
const tones={done:'good',pass:'good',complete:'good',doing:'live',running:'live',queued:'live',active:'live',in_progress:'live',blocked:'attention',stale:'attention',fail:'danger',failed:'danger',error:'danger',interrupted:'danger'};
const tone=s=>tones[String(s).toLowerCase()]||'quiet';
export const eventSummary=e=>e.kind==='task-move'?`${e.ref||'Task'} moved to ${human(e.data?.to||'an unrecorded state')}`:e.kind==='claim'?`${e.ref||'Work'} assigned to ${e.data?.worker||'a worker'}`:e.kind==='proof-report'?`Work report sealed for ${e.ref||'task'}`:e.kind==='session-start'?'Session started':e.summary||human(e.kind);
const human=s=>String(s||'unknown').replaceAll('_',' ').replaceAll('-',' ');
const panel=(title,sub,body,action='')=>`<section class="panel visual-panel"><div class="panel-head"><div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div>${action}</div>${body}</section>`;
const link=(route,text,params={})=>`<a class="text-link" href="${esc(href(route,params))}">${esc(text)} ${icon('arrow')}</a>`;
// Stage display names come from the domain profile (alpaca/profile.py `web` stage_names), set by the
// hub once the overview is read. Without a profile there are no stages to name.
let stageNames={};
export function setStageNames(map){stageNames=map&&typeof map==='object'?map:{};}
// Cockpit cards a profile supplies (alpaca/profile.py `web` cards): each loaded module exports
// render(o, runs) returning HTML and may export bind(). The hub loads them before rendering.
// A named profile that did not load, or a hook that failed, is shown on the cockpit, never
// hidden behind an empty panel (alpaca/profile.py: overview profile.error and profile.hook_errors).
export function profileProblems(o){const p=o?.profile||{},hooks=Object.entries(p.hook_errors||{});if(!p.error&&!hooks.length)return '';return `<section class="notice" id="profile-error" role="alert">${icon('alert')}<div><h3>${p.error?'The domain profile did not load':'The domain profile has failing hooks'}</h3>${p.error?`<p>${esc(p.error)}</p>`:''}${hooks.length?`<ul>${hooks.map(([h,why])=>`<li><code>${esc(h)}</code>: ${esc(why)}</li>`).join('')}</ul>`:''}<p>Its panels stay empty until it is fixed. Run bin/alpaca doctor for the full list.</p></div></section>`;}
function profileCards(cards,o,r){return (cards||[]).map(c=>{try{return c.render(o,r)||'';}catch{return '';}}).join('');}
export function segmented(items,key,{label='Recorded states',route=null,param='status',params={}}={}){
 const groups=new Map();for(const row of items){const v=String(row[key]||'unknown').toLowerCase();groups.set(v,(groups.get(v)||0)+1);}
 const parts=[...groups].sort(([a],[b])=>['done','pass','doing','running','open','blocked','fail'].indexOf(a)-['done','pass','doing','running','open','blocked','fail'].indexOf(b));
 return `<div class="state-distribution"><div class="distribution-label"><span>${esc(label)}</span><strong>${n(items.length)} total</strong></div><div class="segmented-track" role="img" aria-label="${esc(parts.map(([s,c])=>human(s)+': '+c).join(', ')||'No records')}">${parts.map(([s,c])=>`<span class="tone-${tone(s)}" style="flex:${c}" title="${esc(human(s)+': '+c)}"></span>`).join('')}</div><div class="state-legend">${parts.map(([s,c])=>{const body=`<i class="tone-${tone(s)}"></i><span>${esc(human(s))}</span><strong>${n(c)}</strong>`;return route?`<a href="${esc(href(route,{...params,[param]:s}))}">${body}</a>`:`<span>${body}</span>`;}).join('')}</div></div>`;
}
export function ring(value,total,label,sub,cls=''){
 const pct=total?Math.max(0,Math.min(100,value/total*100)):0;
 return `<div class="progress-ring ${cls}"><div class="ring-art"><svg viewBox="0 0 120 120" role="img" aria-label="${esc(value+' of '+total+' '+label)}"><circle class="ring-track" cx="60" cy="60" r="50"/><circle class="ring-fill" cx="60" cy="60" r="50" pathLength="100" stroke-dasharray="${pct} 100" transform="rotate(-90 60 60)"/></svg><div class="ring-number"><strong>${total?Math.round(pct)+'%':'N/A'}</strong><span>${n(value)} / ${n(total)}</span></div></div><div class="ring-caption"><strong>${esc(label)}</strong><span>${esc(sub)}</span></div></div>`;
}
export function dayChart(items,{field='ts',label='Loaded activity',subtitle='Counts describe the records currently displayed.'}={}){
 const days=new Map();for(const item of items){if(!item[field])continue;const d=new Date(typeof item[field]==='number'?item[field]*1000:item[field]);if(!Number.isFinite(+d))continue;const key=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');days.set(key,(days.get(key)||0)+1);}
 const rows=[...days].sort().slice(-14),max=Math.max(1,...rows.map(r=>r[1]));
 return `<section class="mini-chart-panel"><div class="mini-chart-title"><strong>${esc(label)}</strong><span>${esc(subtitle)}${days.size>14?' / Latest 14 dates with records':''}</span></div><div class="day-bars" role="img" aria-label="${esc(rows.map(([d,c])=>d+': '+c).join(', ')||'No dated records')}">${rows.map(([d,c])=>`<div class="day-column" title="${esc(d+': '+c+' records')}"><strong>${n(c)}</strong><i style="height:${Math.max(3,c/max*60)}px"></i><span>${esc(d.slice(5))}</span></div>`).join('')||'<p class="muted">No dated records captured.</p>'}</div></section>`;
}
export function categoryBars(items,key,label){
 const groups=new Map();for(const row of items){const keyValue=row[key]||'unknown';groups.set(keyValue,(groups.get(keyValue)||0)+1);}
 const rows=[...groups].sort((a,b)=>b[1]-a[1]),max=Math.max(1,...rows.map(r=>r[1]));
 return `<section class="mini-chart-panel"><div class="mini-chart-title"><strong>${esc(label)}</strong><span>${items.length} loaded records</span></div><div class="category-bars">${rows.map(([name,c])=>`<div><span>${esc(human(name))}</span><i><b style="width:${100*c/max}%"></b></i><strong>${c}</strong></div>`).join('')||'<p class="muted">No records loaded.</p>'}</div></section>`;
}
export function stageMap(stages){
 return `<div class="flow-map">${stages.map((s,i)=>`<a class="flow-node tone-border-${tone(s.status)}" href="${esc(href('work',{tab:'outcomes',stage:s.stage}))}" title="${esc(s.reason||'Open the recorded check')}"><div class="flow-node-top"><span>${String(i+1).padStart(2,'0')}</span><i class="status-symbol tone-text-${tone(s.status)}">${icon(s.status==='PASS'?'check':s.status==='RUNNING'?'activity':s.status==='FAIL'?'close':'alert')}</i></div><strong>${esc(stageNames[s.stage]||s.stage)}</strong><span class="flow-node-state tone-text-${tone(s.status)}">${esc(human(s.status))}</span><small>Recorded: ${esc(s.recorded_status||'none')}</small></a>`).join('')}</div>`;
}
// Every live work session side by side, each with what it is doing: the tasks it holds a claim on
// (title, purpose, status, as on the focus card), the session title and the owner's latest ask
// from its transcript. `live` is pulse.now.sessions.work from /board/data.json; `transcripts` is
// the analytics fold (/data.json), which lags the record by up to a minute. Without `live` the
// panel falls back to the claimed tasks in the overview, grouped by their assigned session.
function sessionsPanel(o,live,transcripts){
 const task=id=>o.tasks.find(t=>t.id===id)||{id,title:id};
 const talk=new Map((transcripts||[]).map(s=>[s.sid,s]));
 let rows=Array.isArray(live)?live.filter(s=>s.active).map(s=>({sid:s.sid,beat:s.last_beat,tool:s.last_tool,claims:s.claims||[]})):null;
 if(!rows){const by=new Map();for(const t of o.tasks.filter(t=>t.status==='doing'&&t.assigned_session)){const g=by.get(t.assigned_session)||{sid:t.assigned_session,beat:t.updated_at,tool:null,claims:[]};g.claims.push(t.id);by.set(t.assigned_session,g);}rows=[...by.values()];}
 rows.sort((a,b)=>(b.claims.length?1:0)-(a.claims.length?1:0)||(Date.parse(b.beat)||0)-(Date.parse(a.beat)||0));
 const idle=Array.isArray(live)?live.filter(s=>!s.active).length:0,unclaimed=rows.filter(s=>!s.claims.length).length;
 const taskRow=id=>{const t=task(id);return `<div class="ls-task"><div class="ls-task-head"><span class="task-number">${String(t.number||Number(String(t.id).replace(/\D/g,''))||'').padStart(2,'0')}</span><button data-task="${esc(t.id)}">${esc(short(t.title||t.id,120))}</button><span class="status-chip tone-${tone(t.status)}">${esc(human(t.status||'unknown'))}</span></div>${t.purpose||t.description?`<p class="ls-purpose">${esc(short(t.purpose||t.description,220))}</p>`:''}<small class="mono">${esc(t.id)}${t.op?' / '+esc(t.op):''}${t.updated_at?' / updated '+esc(age(t.updated_at)):''}</small></div>`;};
 const cards=rows.map(s=>{const tr=talk.get(s.sid)||{},asks=tr.human_prompts||[],ask=asks[asks.length-1];
  return `<article class="live-session ${s.claims.length?'':'is-unclaimed'}"><div class="ls-top"><span class="live-dot"></span><div class="ls-name"><strong>${esc(short(tr.title||'Session title not captured yet',90))}</strong><small><a class="mono" href="${esc(href('sessions',{sid:s.sid}))}" title="${esc(s.sid)}">${esc(String(s.sid).slice(0,8))}</a> &middot; <span title="${esc(date(s.beat))}">beat ${esc(age(s.beat))}</span>${s.tool?' &middot; '+esc(short(s.tool,24)):''}</small></div></div>${ask?`<p class="ls-ask" title="${esc(date(ask.ts))}"><span>Latest ask &middot; ${esc(age(ask.ts))}</span>${esc(short(String(ask.text).split('\n')[0],200))}</p>`:''}${s.claims.length?s.claims.map(taskRow).join(''):`<div class="ls-unclaimed">${icon('alert')}<p><strong>No task claimed.</strong> This session's work is not tied to a task in the record. Its next prompt reminds it to run <code>bin/alpaca task claim</code>.</p></div>`}</article>`;}).join('');
 return `<section class="panel visual-panel live-sessions"><div class="panel-head"><div><h2>Parallel sessions</h2><p>${rows.length} live now${unclaimed?' &middot; '+unclaimed+' without a claimed task':''}${idle?' &middot; '+idle+' idle in the recent window':''}${Array.isArray(live)?'':' &middot; from task claims only'}</p></div>${link('sessions','All sessions')}</div>${cards?`<div class="live-session-grid">${cards}</div>`:'<p class="visual-empty">No work session is live.</p>'}</section>`;
}
export function renderCockpit(o,r,h,{paused=false,live=null,transcripts=null,cards=[]}={}){
 startSystem();for(const c of cards){try{c.bind?.();}catch{}}
 const runsOn=(o.profile?.pages||[]).includes('runs');
 const open=o.tasks.filter(t=>!['done','cancelled','canceled'].includes(t.status));
 // The assignment card follows the open work: a claimed task first, then the newest record.
 const focus=open.slice().sort((a,b)=>Number(Boolean(b.claimant))-Number(Boolean(a.claimant))||String(b.updated_at||b.id).localeCompare(String(a.updated_at||a.id)))[0];
 const op=o.ops.find(x=>x.id===focus?.op)||o.ops.find(x=>x.status!=='closed');
 const opTasks=o.tasks.filter(t=>t.op===op?.id),done=opTasks.filter(t=>t.status==='done');
 const latest=[...o.tasks].filter(t=>t.status==='done').sort((a,b)=>(Date.parse(b.completed_at)||0)-(Date.parse(a.completed_at)||0)).slice(0,3);
 const active=(r.items||[]).filter(run=>o.active_jobs.includes(run.id)),stages=o.stages||[],blocked=stages.filter(s=>!['PASS','RUNNING','QUEUED'].includes(s.status));
 const currentPass=stages.filter(s=>s.status==='PASS').length,recordedPass=stages.filter(s=>s.recorded_status==='PASS').length;
 const recent=h.items.slice(0,6),assignment=focus?.assigned_session;
 const attention=o.items.filter(item=>!['PASS','RUNNING','QUEUED'].includes(item.status)).length;
 return `<div class="cockpit-heading"><div><span class="eyebrow">LIVE ENGINEERING VIEW</span><h1>Cockpit</h1><p>What is moving, what finished, and what needs attention.</p></div><div class="cockpit-controls"><span class="live-label ${paused?'paused':''}"><i></i>${paused?'Updates paused':'Refreshes every 15s'}</span><button class="button" data-action="cockpit-pause" aria-pressed="${paused}">${icon(paused?'refresh':'pause')}${paused?'Resume':'Pause'}</button><button class="button" data-action="cockpit-present" aria-pressed="false">${icon('sessions')}<span>Focus view</span></button></div></div>
 ${profileProblems(o)}
 <div class="cockpit-hero"><section class="focus-card"><div class="focus-card-top"><span class="eyebrow">${focus?(focus.claimant?'CURRENT ASSIGNMENT':'NEXT OPEN TASK'):'CHECKLIST'}</span><span class="status-chip tone-${focus?tone(focus.status):'quiet'}">${focus?esc(human(focus.status)):'No open work'}</span></div>${focus?`<div class="focus-title"><span class="task-number">${String(focus.number||Number(focus.id.replace(/\D/g,''))).padStart(2,'0')}</span><button data-task="${esc(focus.id)}">${esc(short(focus.title,190))}</button></div><p class="focus-purpose">${esc(short(focus.purpose||focus.reason||op?.done_when,210))}</p><div class="focus-footer"><div><span>Assigned session</span>${assignment?`<a href="${esc(href('sessions',{sid:assignment}))}">${icon('sessions')}${esc(short(assignment,22))}</a>`:`<strong>${esc(focus.claimant?'Worker: '+short(focus.claimant,20):'Unassigned')}</strong>`}</div><div><span>Last task record</span><strong title="${esc(date(focus.updated_at))}">${esc(age(focus.updated_at))}</strong></div>${runsOn?`<div><span>Active run</span><strong>${active.length?active.map(run=>esc((run.design||'')+' / '+(stageNames[run.current_stage]||run.current_stage||'')+' running')).join(', '):'None running'}</strong></div>`:''}${link('work','Open checklist',{op:focus.op})}</div>`:`<div class="focus-empty">${icon('check')}<h2>No unfinished task is recorded.</h2><p>Review current evidence before accepting the work or starting new work.</p>${link('work','Review work and evidence')}</div>`}</section>
 <section class="panel operation-progress">${ring(done.length,opTasks.length,'Operation tasks complete',op?.id||'No current operation')}<div><a href="${esc(href('work',op?{op:op.id}:{}))}">${esc(short(op?.title||'No open operation',90))}</a><p>Recorded completion with linked work reports. This is a task count, not an estimate of time remaining.</p></div></section></div>
 ${sessionsPanel(o,live,transcripts)}
 <div class="cockpit-stats"><a href="#work" class="cockpit-stat"><span class="stat-icon">${icon('work')}</span><div><strong>${n(open.length)}</strong><span>unfinished tasks</span></div><small>${n(o.tasks.filter(t=>t.status==='done').length)} completed overall</small></a>${runsOn?`<a href="#runs" class="cockpit-stat"><span class="stat-icon ${active.length?'active':''}">${icon('runs')}</span><div><strong>${n(active.length)}</strong><span>active runs</span></div><small>${active.length?'Current checked execution':'No run currently active'}</small></a>`:''}${o.items.length?`<a href="#work?tab=outcomes" class="cockpit-stat"><span class="stat-icon attention">${icon('alert')}</span><div><strong>${n(attention)}</strong><span>outcomes need attention</span></div><small>${n(o.counts.items_pass)} / ${n(o.items.length)} currently passing</small></a>`:''}<a href="#activity" class="cockpit-stat"><span class="stat-icon">${icon('activity')}</span><div><strong>${recent.length?esc(age(recent[0].ts)):'None'}</strong><span>last meaningful activity</span></div><small>${recent.length?esc(human(recent[0].kind)):'No work event recorded'}</small></a></div>
 ${profileCards(cards,o,r)}
 <div class="cockpit-main"><div class="cockpit-primary">
 ${runsOn?panel('Execution','Active jobs are shown only when current receipt checks confirm them',active.length?active.map(run=>`<div class="active-run"><div class="run-pulse">${icon('activity')}</div><div><strong>${esc(run.design)} / ${esc(stageNames[run.current_stage]||run.current_stage)}</strong><p>${esc(run.reason)}</p><small>Started ${esc(date(run.started_at))}</small></div>${link('runs','Follow output',{run:run.id})}</div>`).join(''):`<div class="idle-run">${icon('pause')}<div><strong>No run is active</strong><p>${r.items?.length?'Last captured run: '+esc(r.items[0].design||'design')+' / '+esc(r.items[0].stage)+', '+esc(human(r.items[0].verdict))+'.':'No run receipts have been recorded.'} Software and review work can continue while no run is active.</p></div>${link('runs','Inspect logs')}</div>`):''}
 ${panel('Recently completed','What the work delivered, with its recorded completion',latest.length?`<div class="completion-cards">${latest.map(t=>`<article><span class="completion-mark">${icon('check')}</span><div><span class="eyebrow">${esc(t.id)} / ${esc(date(t.completed_at))}</span><button data-task="${esc(t.id)}">${esc(short(t.title,95))}</button><p>${esc(short(t.report?.result||t.report?.what||'Open the work record for the linked report and completion evidence.',160))}</p><div>${t.completed_session?link('sessions','Completing session',{sid:t.completed_session}):'<span class="muted">Completing session not recorded</span>'}${t.proof?link('library','Proof',{path:String(t.proof).replace(/^local:/,'')}):''}</div></div></article>`).join('')}</div>`:'<div class="visual-empty">No task completion is recorded yet.</div>',link('work','Completed work',{status:'done'}))}</div>
 <aside class="cockpit-secondary">${panel('Next engineering action',blocked.length?'A fresh check is required before accepting the work':'Follow the current assignment',`<div class="next-action"><span class="next-symbol">${icon(blocked.length?'alert':'arrow')}</span><h3>${esc(blocked.length?stageNames[blocked[0].stage]||blocked[0].stage:'Continue recorded work')}</h3><p>${esc(blocked[0]?.reason||focus?.purpose||'Review the checklist and choose the next justified task.')}</p>${blocked.length?link('work','See the evidence gap',{tab:'outcomes',stage:blocked[0].stage}):link('work','Open work record')}</div>`)}
 ${panel('Latest activity','Task and run updates from the shared record',`<div class="cockpit-timeline">${recent.map(e=>`<a href="${esc(href('activity',e.ref?{ref:e.ref}:{session:e.session||''}))}"><span class="timeline-dot tone-${tone(e.kind.includes('failed')?'fail':e.kind==='task-move'?e.data?.to||'open':'open')}"></span><div><strong>${esc(short(eventSummary(e),115))}</strong><small>${esc(human(e.kind))} / ${esc(age(e.ts))}</small></div></a>`).join('')||'<p class="visual-empty">No meaningful activity captured.</p>'}</div>`,link('activity','History',{kind:'progress'}))}
 ${panel('Capture health','Collection problems remain visible',`<div class="capture-health"><span class="status-chip tone-${o.capture.status==='ok'?'good':o.capture.status==='pending'?'attention':tone(o.capture.status)}">${esc(human(o.capture.status))}</span><p>${n(o.capture.errors?.length)} recent capture issues recorded.</p>${o.capture.errors?.length?link('activity','Inspect capture issues',{q:'failed',kind:'all'}):'<small>Usage and conversation coverage are available in Sessions.</small>'}</div>`)}
 </aside></div>
 ${systemPanel()}`;
}
export function renderWorkCards(items){return `<div class="work-cards">${items.map(t=>{const r=t.report,done=t.status==='done',historical=!done&&t.last_completion;return `<article class="work-card tone-border-${tone(t.status)}"><div class="work-card-heading"><span class="task-number">${String(t.number||Number(t.id.replace(/\D/g,''))).padStart(2,'0')}</span><div><div class="work-card-meta"><span class="mono">${esc(t.id)} / ${esc(t.op)}</span><span class="status-chip tone-${tone(t.status)}">${esc(human(t.status))}</span>${t.status!=='done'?(t.contract?`<span class="status-chip tone-good" title="${esc('Done bar: '+(t.contract.done_bar||[]).join('; '))}">Contract</span>`:'<span class="status-chip tone-attention" title="No input, expected output, done bar or fail case recorded">No contract</span>'):''}</div><button class="work-card-title" data-task="${esc(t.id)}">${esc(t.title)}</button></div></div><p class="work-purpose">${esc(short(t.description||t.purpose||t.reason||'No purpose recorded yet.',220))}</p><div class="work-delivery">${historical?'<p class="inline-warning">Reopened. Report below describes earlier work.</p>':''}${r?`<div><span>${historical?'EARLIER WORK':'WHAT WAS DONE'}</span><p>${esc(short(r.what||'Work summary not recorded.',190))}</p></div>${r.result?`<div class="work-result"><span>${historical?'EARLIER RESULT':'RESULT'}</span><p>${esc(short(r.result,180))}</p></div>`:''}<details class="work-method"><summary>${icon('file')}${r.how?'Read recorded method':'Method not recorded'}</summary><p>${esc(short(r.how||'No method section is present in the linked report.',500))}</p></details>`:done?`<div class="work-report-empty">${icon('file')}<p>Completion is recorded; no readable work report is linked.</p></div>`:`<div class="work-report-empty"><p>${esc(t.status==='doing'?'In progress':t.status==='blocked'?'Blocked'+(t.reason?': '+short(t.reason,140):''):'Not started')}</p></div>`}</div><div class="work-card-footer"><div><span>${done?'Completed':'Last task update'}</span><strong>${esc(date(done?t.completed_at:t.updated_at))}</strong>${(done?t.completed_session:t.assigned_session)?`<a href="${esc(href('sessions',{sid:done?t.completed_session:t.assigned_session}))}" title="${esc(done?t.completed_session:t.assigned_session)}">${done?'Completed by':'Assigned to'} ${esc(short(done?t.completed_session:t.assigned_session,24))}</a>`:`<small>${esc(done?'Completing session not recorded':t.claimant?'Worker: '+short(t.claimant,30):'No assigned session')}</small>`}</div><button class="button" data-task="${esc(t.id)}">Record & proof ${icon('arrow')}</button></div></article>`;}).join('')}</div>`;}
// Newest first on a left rail, one color per state. Tasks sort by completion (done) or last update;
// outcomes sort by their last recorded change. A missing timestamp sinks to the end, never invents one.
const tlTones={done:'good',pass:'good',complete:'good',doing:'live',running:'live',active:'live',in_progress:'live',blocked:'attention',stale:'attention',fail:'danger',failed:'danger',error:'danger',open:'open'};
const tlTone=s=>tlTones[String(s).toLowerCase()]||'quiet';
const tlMs=v=>{if(!v)return NaN;const d=new Date(typeof v==='number'?v*1000:v);return +d;};
const tlDay=ms=>{const d=new Date(ms),t=new Date();t.setHours(0,0,0,0);const k=new Date(d);k.setHours(0,0,0,0);const diff=Math.round((t-k)/86400000);const label=d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});return diff===0?'Today &middot; '+esc(label):diff===1?'Yesterday &middot; '+esc(label):esc(label);};
const tlLegend=kind=>`<div class="tl-legend" aria-label="Color key">${(kind==='outcomes'?[['good','Pass'],['attention','Blocked'],['danger','Failed']]:[['good','Done'],['live','In progress'],['open','Open'],['attention','Blocked'],['danger','Failed']]).map(([t,l])=>`<span><i class="tl-dot tl-${t}"></i>${l}</span>`).join('')}</div>`;
export function renderWorkTimeline(items,kind='tasks'){
 const outcomes=kind==='outcomes';
 const rows=items.map(t=>{const done=t.status==='done';const at=outcomes?(t.updated_at||t.recorded_completed_at||t.verified_at):((done&&t.completed_at)||t.updated_at||t.created_at);const what=outcomes?(t.recorded_completed_at&&t.status!=='PASS'?'Last recorded':t.status==='PASS'?'Passed':'Checked'):done?'Completed':t.updated_at&&t.updated_at!==t.created_at?'Updated':'Created';return {t,at,ms:tlMs(at),what};}).sort((a,b)=>(Number.isNaN(b.ms)?-Infinity:b.ms)-(Number.isNaN(a.ms)?-Infinity:a.ms));
 let day='',html='';
 for(const {t,at,ms,what} of rows){
  const key=Number.isNaN(ms)?'none':new Date(ms).toDateString();
  if(key!==day){day=key;html+=`<li class="tl-day"><span>${key==='none'?'No timestamp recorded':tlDay(ms)}</span></li>`;}
  const tn=tlTone(t.status),num=String(t.number||Number(String(t.id).replace(/\D/g,''))).padStart(2,'0');
  const time=Number.isNaN(ms)?'--:--':new Date(ms).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});
  const r=t.report,done=t.status==='done';
  const sub=outcomes?(t.reason||'Open for method, result and evidence.'):(r?.result||r?.what||t.description||t.purpose||t.reason||'No purpose recorded yet.');
  const sid=outcomes?t.recorded_completed_session:(done?t.completed_session:t.assigned_session);
  const meta=[`<span class="mono">${esc(t.id)} / ${esc(outcomes?(stageNames[t.stage]||t.stage):t.op)}</span>`,`<span>${what} ${esc(date(at))}</span>`];
  if(outcomes&&t.recorded_status&&t.recorded_status!==t.status)meta.push(`<span>Recorded ${esc(human(t.recorded_status))}</span>`);
  if(sid)meta.push(`<a href="${esc(href('sessions',{sid}))}" title="${esc(sid)}">${icon('sessions')}${esc(short(sid,12))}</a>`);
  else if(!outcomes&&t.claimant)meta.push(`<span>Worker: ${esc(short(t.claimant,24))}</span>`);
  if(!outcomes)meta.push(t.proof?`<span class="tl-proof tone-text-good">${icon('check')}Proof linked</span>`:`<span class="muted">No proof</span>`);
  if(!outcomes&&t.status!=='done')meta.push(t.contract?`<span class="tl-proof tone-text-good" title="${esc('Done bar: '+(t.contract.done_bar||[]).join('; '))}">${icon('check')}Contract</span>`:'<span class="tone-text-attention" title="No input, expected output, done bar or fail case recorded">No contract</span>');
  html+=`<li class="tl-item tl-${tn}"><div class="tl-when"><strong>${esc(time)}</strong><small>${esc(age(at))}</small></div><span class="tl-node" aria-hidden="true"></span><article class="tl-card"><div class="tl-head"><span class="task-number">${num}</span><button class="tl-title" ${outcomes?'data-outcome':'data-task'}="${esc(t.id)}">${esc(t.title)}</button><span class="status-chip tl-chip">${esc(human(t.status))}</span></div><p class="tl-sub">${esc(short(sub,220))}</p><div class="tl-meta">${meta.join('')}</div></article></li>`;
 }
 return `${tlLegend(kind)}<ol class="tl">${html}</ol>`;
}
export function runVisuals(rows,selected){
 const stages=selected?.stages||[],max=Math.max(1,...stages.map(s=>s.elapsed_s||0));
 return `<div class="page-visuals">${segmented(rows,'verdict',{label:'Captured run results',route:'runs'})}${stages.length?`<section class="mini-chart-panel"><div class="mini-chart-title"><strong>Stage duration</strong><span>Measured duration within the selected run</span></div><div class="duration-bars">${stages.map(s=>`<a href="${esc(href('runs',{run:selected.id,receipt:s.receipt_id}))}"><span>${esc(stageNames[s.stage]||s.stage)}</span><i><b class="tone-${tone(s.verdict)}" style="width:${s.elapsed_s==null?0:100*s.elapsed_s/max}%"></b></i><strong>${s.elapsed_s==null?'Not recorded':s.elapsed_s<60?Math.round(s.elapsed_s)+'s':(s.elapsed_s/60).toFixed(1)+'m'}</strong></a>`).join('')}</div></section>`:dayChart(rows,{field:'started_at',label:'Attempts by day',subtitle:'Recorded attempts in the filtered result set'})}</div>`;
}
export function collectionVisuals(items,key,label){
 const groups=new Map();for(const item of items){const v=item[key]||'unknown';groups.set(v,(groups.get(v)||0)+1);}
 return `<div class="collection-overview">${[...groups].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,c])=>`<div><span class="collection-icon">${icon(key==='ext'?'file':'messages')}</span><strong>${n(c)}</strong><span>${esc(human(k))}</span><i style="--portion:${items.length?c/items.length*100:0}%"></i></div>`).join('')}</div><p class="visual-scope">${esc(label)}</p>`;
}
