import {icon, hydrate} from './icons.js';
import {renderAnalytics, analyticsIndex, renderCrew} from './analytics.js';
import {renderCockpit, renderWorkCards, renderWorkTimeline, segmented, dayChart, runVisuals, collectionVisuals, categoryBars, eventSummary, setStageNames, profileProblems} from './cockpit.js';
import {createLive} from './live.js';
import {patch as patchHtml, render as renderHtml} from './morph.js';
import {changedFlags, dependsOn, autoRefresh, needs, createDirty} from './liveflags.js';
import {runsOverview, runDashboard, renderScan, renderFindings, renderLogLines, jumpToLine, renderReview, reviewLines, renderContract} from './runlog.js';
const $ = (q, root=document) => root.querySelector(q);
const readerEngaged=()=>document.hidden||document.activeElement?.closest('#main,#navigation')||$('#inspector').open||$('#command').open||(state.route==='cockpit'&&state.cockpitPaused);
// 'runs' and 'live' are profile pages: shown only when the domain profile turns them on
// (alpaca/profile.py `web` pages). Without a profile the hub has no run or live-log page.
const ALL_PAGES = [ ['cockpit','Cockpit'],['overview','Overview'],['work','Work & evidence'],['runs','Runs & logs'],['live','Live logs'],['activity','Activity'],['messages','Messages'],['library','Library'],['sessions','Sessions'] ];
const PROFILE_PAGES = ['runs','live'];
const profileOn = id => (state.overview?.profile?.pages||[]).includes(id);
function visiblePages(){return ALL_PAGES.filter(([id])=>!PROFILE_PAGES.includes(id)||profileOn(id));}
const state = {overview:null, runs:null, sessions:null, documents:null, route:'cockpit', params:new URLSearchParams(), ticket:0, log:null, timer:null, history:null, detail:null, mounts:0, mountY:0};
// One dirty flag per client cache (liveflags.js FLAGS) with a generation each: a fetch clears its flag
// only when no newer revision marked it while the fetch was in flight.
const flags=createDirty();
const liveParams=()=>({sid:state.params.get('sid'),view:state.params.get('view')||'analysis'});
const esc = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const count = value => Number(value||0).toLocaleString();
const date = value => {if(!value)return 'Not recorded'; const d=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(+d)?String(value):d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});};
const relative = value => {const d=new Date(typeof value==='number'?value*1000:value);const m=Math.floor((Date.now()-d)/60000);return !value||Number.isNaN(m)?'Not recorded':m<1?'Just now':m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:date(value);};
const duration = value => value==null?'Not recorded':value<60?`${Math.round(value)}s`:value<3600?`${Math.round(value/60)}m`:`${Math.floor(value/3600)}h ${Math.round(value%3600/60)}m`;
const short = (value,n=110) => String(value??'').length>n?String(value).slice(0,n)+'...':String(value??'');
const human = value => String(value||'unknown').replace(/[_-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const badge = value => `<span class="badge ${esc(['pass','done','complete','blocked','stale','open','fail','error','running','active','doing','in_progress'].includes(String(value).toLowerCase())?String(value).toLowerCase():'neutral')}"><i class="badge-dot"></i>${esc(human(value))}</span>`;
const stageName = value=>(state.overview?.profile?.stage_names||{})[value]||human(value);
const href=(page,params={})=>'#'+page+(Object.keys(params).length?'?'+new URLSearchParams(params):'');
const link=(page,label,params={},cls='text-link')=>`<a class="${cls}" href="${esc(href(page,params))}">${esc(label)}${icon('arrow')}</a>`;
const empty=(title,body,symbol='file')=>`<div class="empty">${icon(symbol)}<h3>${esc(title)}</h3><p>${esc(body)}</p></div>`;
const heading=(title,subtitle,action='',eyebrow='WORKSPACE')=>`<div class="page-heading"><div><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${action}</div>`;
const panel=(title,body,action='',subtitle='')=>`<section class="panel"><div class="panel-head"><div><h2>${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div>${action}</div>${body}</section>`;
const metric=(label,value,note,symbol)=>`<div class="metric"><div class="metric-label">${esc(label)}${icon(symbol)}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;
const search=(placeholder,value='',name='q')=>`<label class="filter-input">${icon('search')}<input data-filter="${name}" type="search" placeholder="${esc(placeholder)}" value="${esc(value)}" aria-label="${esc(placeholder)}"></label>`;
const select=(name,choices,current,label)=>`<select class="filter-select" data-filter="${name}" aria-label="${esc(label)}">${choices.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('')}</select>`;
const errorView=err=>`<div class="error-box"><h2>This view could not be loaded</h2><p>${esc(err.message||err)}</p><button class="button" data-action="retry">Try again</button></div>`;
// The sign-in and workspace takeovers park the first render's reads in the Cache API (vault.js,
// prefetchWorkspace). The first route takes each parked response once; the cache is then dropped.
const HANDOFF='alpaca-handoff',HANDOFF_MAX_AGE_MS=60000;
let handoff=(()=>{try{return window.caches?caches.open(HANDOFF).catch(()=>null):null;}catch{return null;}})();
async function fromHandoff(url){if(!handoff)return null;try{const cache=await handoff;const r=cache&&await cache.match(url);if(!r)return null;await cache.delete(url);if(Date.now()-Number(r.headers.get('X-Handoff-At')||0)>HANDOFF_MAX_AGE_MS)return null;return await r.json();}catch{return null;}}
function dropHandoff(){if(!handoff)return;handoff=null;try{caches.delete(HANDOFF).catch(()=>{});}catch{}}
async function api(path, params={}){const qs=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==null&&v!==undefined&&v!==''));const url=path+(qs.size?'?'+qs:'');const parked=await fromHandoff(url);if(parked)return parked;const r=await fetch(url,{credentials:'same-origin'});if(!r.ok){let reason;try{reason=(await r.json()).error;}catch{}const error=Error(reason||`The server returned ${r.status}. ${r.status===401?'Sign in and refresh this page.':'Please try again.'}`);error.status=r.status;throw error;}return r.json();}
async function loadOverview(force=false){if(!state.overview||force||flags.dirty.overview){const seen=flags.seen('overview');state.overview=await api('/hub/overview.json');flags.settle('overview',seen);setStageNames(state.overview?.profile?.stage_names||{});}return state.overview;}
async function loadRuns(force=false){if(!state.runs||force||flags.dirty.runs){const seen=flags.seen('runs');state.runs=await api('/hub/runs.json');flags.settle('runs',seen);}return state.runs;}
async function loadSessions(force=false){if(!state.sessions||force||flags.dirty.sessions){const seen=flags.seen('sessions');state.sessions=await api('/data.json');flags.settle('sessions',seen);}return state.sessions;}
function mount(html){state.mounts++;state.mountY=window.scrollY;$('#main').innerHTML=html;hydrate($('#main'));}
function toast(message){const e=$('#toast');e.textContent=message;e.style.display='block';setTimeout(()=>e.style.display='none',3500);}
function updateChrome(){const o=state.overview;$('#project-name').textContent=o?.project?.name||'Alpaca';const nav=visiblePages().map(([id,label],i)=>`${id==='messages'?'<div class="nav-divider"></div>':''}<a class="nav-link ${id===state.route?'active':''}" href="#${id}" ${id===state.route?'aria-current="page"':''}>${icon(id)}<span>${label}</span>${id==='live'&&o?.active_jobs?.length?`<span class="nav-count nav-live">${o.active_jobs.length}</span>`:''}${id==='work'&&o?`<span class="nav-count">${o.tasks.filter(t=>!['done','cancelled','canceled'].includes(t.status)).length}</span>`:''}</a>`).join('');if(nav!==state.nav){state.nav=nav;$('#navigation').innerHTML=nav;}$('#crumb').textContent=visiblePages().find(p=>p[0]===state.route)?.[1]||'Overview';}
function verifiedNote(o){const blocked=(o.items||[]).filter(x=>x.status!=='PASS');if(!blocked.length)return '';return `<div class="notice">${icon('alert')}<div><h3>${blocked.length} acceptance outcomes need current evidence</h3><p>Recorded completions are preserved. Current checks identify expired, missing, or changed evidence before work can resume.</p></div>${link('work','Review evidence',{tab:'outcomes'})}</div>`;}
function eventRows(items,full=false){return items.map(e=>`<div class="activity-item"><span class="event-symbol">${icon(/msg/.test(e.kind)?'messages':/task|check|proof/.test(e.kind)?'work':/run|receipt|job/.test(e.kind)?'runs':'activity')}</span><div class="event-text"><h3>${esc(e.kind==='run'&&e.ref?stageName(e.ref)+': ':'')}${esc(eventSummary(e))}</h3><div class="event-meta"><span>${esc(human(e.kind))}</span>${e.ref?`<a href="${esc(href('work',{q:e.ref}))}">${esc(e.ref)}</a>`:''}${e.session?`<a href="${esc(href('sessions',{sid:e.session}))}">${esc(short(e.actor||e.session,26))}</a>`:''}</div>${full?`<details><summary>View recorded context</summary><pre class="raw-data">${esc(JSON.stringify(e.data,null,2))}</pre></details>`:''}</div><span class="event-time">${esc(relative(e.ts))}</span></div>`).join('');}
function docMini(doc){return `<a class="doc-mini" href="${esc(href('library',{path:doc.path}))}"><span class="doc-icon">${icon('file')}</span><span><strong>${esc(short(doc.title,90))}</strong><small>${esc(human(doc.category))} &middot; ${esc(date(doc.mtime))}${doc.sealed?' &middot; Sealed proof':''}</small></span></a>`;}
// Cockpit cards a domain profile supplies (alpaca/profile.py `web` cards), loaded once per module.
// A card module exports render(o, runs) and may export bind(); a broken card is left out.
const cardModules=new Map();
async function loadCards(o){const out=[];for(const c of o?.profile?.cards||[]){try{if(!cardModules.has(c.module))cardModules.set(c.module,await import(c.module));const m=cardModules.get(c.module);if(typeof m.render==='function')out.push({id:c.id,render:m.render,bind:m.bind});}catch{}}return out;}
async function cockpit(ticket,automatic=false){
 const focusedAction=document.activeElement?.dataset?.action;
 const [o,r,h,b,a]=await Promise.all([loadOverview(),loadRuns(),api('/hub/history.json',{limit:6,kind:'progress'}),api('/board/data.json').catch(()=>null),loadSessions().catch(()=>null)]);if(ticket!==state.ticket)return;if(automatic&&readerEngaged())return false;
 const cards=await loadCards(o);if(ticket!==state.ticket)return;
 const html=renderCockpit(o,r,h,{paused:Boolean(state.cockpitPaused),live:b?.pulse?.now?.sessions?.work||null,transcripts:a?.sessions||null,cards});
 // A live refresh re-renders only when the record changed (the host panel updates itself, and
 // "Nm ago" labels tick every minute), and at least every 5 minutes so those labels stay current.
 const same=html.replace(/<section[^>]*id="sys-panel"[\s\S]*?<\/section>/,'').replace(/\b\d+[smhd] ago\b|just now/g,'');
 if(automatic&&same===state.cockpitSame&&$('.mx-panel')&&Date.now()-(state.cockpitAt||0)<300000)return;state.cockpitSame=same;state.cockpitAt=Date.now();
 mount(html);
 if(focusedAction?.startsWith('cockpit-'))$(`[data-action="${CSS.escape(focusedAction)}"]`)?.focus();
 const button=$('[data-action="cockpit-present"]');if(button){button.setAttribute('aria-pressed',String(document.body.classList.contains('presentation')));button.querySelector('span').textContent=document.body.classList.contains('presentation')?'Exit focus view':'Focus view';}
}
async function overview(ticket,automatic=false){const [o,h,docs,r]=await Promise.all([loadOverview(),api('/hub/history.json',{limit:5}),api('/hub/documents.json',{limit:4}),loadRuns()]);if(ticket!==state.ticket)return;if(automatic&&readerEngaged())return false;const active=o.tasks.filter(t=>!['done','cancelled','canceled'].includes(t.status));const done=o.tasks.filter(t=>t.status==='done');const lastRun=r.items?.[0];
mount(heading('A clear view of the work.','Follow progress, understand decisions, and trace every result to its evidence.',link('activity','Explore activity',{},'button'),'OPERATIONS OVERVIEW')+
profileProblems(o)+verifiedNote(o)+`<div class="metrics">${metric('Work in progress',count(active.length),`${count(o.tasks.length)} tasks across ${count(o.ops.length)} operations`,'work')}${o.items.length?metric('Current acceptance',`${count(o.counts.items_pass)}<small>/ ${count(o.items.length)}</small>`,'Passing with current evidence','check'):''}${metric('Completed tasks',count(done.length),'Recorded work and linked proof','file')}${profileOn('runs')?metric('Active runs',count(o.active_jobs?.length),lastRun?`Last result: ${esc(stageName(lastRun.stage))} &middot; ${esc(human(lastRun.verdict))}`:'No run receipt recorded','runs'):''}</div>
<div class="columns"><div class="stack">${panel('Work in focus',active.filter(t=>t.status==='doing'||t.claimant).slice(0,2).map(t=>`<div class="workstream"><span class="eyebrow">CURRENT ASSIGNMENT / ${esc(t.id)}</span><button class="workstream-title" style="text-align:left;padding:8px 0 0" data-task="${esc(t.id)}">${esc(t.title)}</button><small>${esc(t.reason||'Open the task for its scope, report, and evidence.')}</small></div>`).join('')+o.ops.filter(op=>op.status!=='closed').slice(-4).reverse().map(op=>{const pct=op.tasks_total?Math.round(op.tasks_done/op.tasks_total*100):0;return `<div class="workstream"><div class="workstream-top"><div><a class="workstream-title" href="${esc(href('work',{op:op.id}))}">${esc(op.title)}</a><small>${esc(op.id)} &middot; ${esc(short(op.done_when||'Open the work record for scope and next actions',130))}</small></div>${badge(op.status)}</div><div class="progress-track"><span style="width:${pct}%"></span></div><div class="progress-caption"><span>${op.tasks_done} of ${op.tasks_total} tasks recorded complete</span><span>${pct}%</span></div></div>`;}).join('')||empty('No open operations','Work will appear here when an operation is recorded.','work'),link('work','All work'))}
${panel('Recent work',`<div class="activity-list">${eventRows(h.items)}</div>`,link('activity','Full history'),'Meaningful changes from the shared record')}
</div><div class="stack">${(o.stages||[]).length?panel(`${o.profile?.name||'Stage'} readiness`,`<div class="stage-list">${(o.stages||[]).slice(0,11).map((s,i)=>`<a class="stage-row" href="${esc(href('work',{tab:'outcomes',stage:s.stage}))}"><span class="stage-symbol ${s.status==='PASS'?'pass':''}">${s.status==='PASS'?icon('check'):String(i+1).padStart(2,'0')}</span><span style="color:var(--text)">${esc(stageName(s.stage))}</span>${badge(s.status)}</a>`).join('')}</div><div class="panel-foot">Current evidence checked ${esc(date(o.stages?.[0]?.verified_at))}. ${profileOn('runs')?link('runs','Inspect run history'):''}</div>`,'','Current checks for the profile stages'):''}
${panel('Capture status',`<div class="panel-body">${o.profile?.name?`<div class="link-row">${badge(o.capture?.profile?.status||'unknown')}<span class="muted">${esc(o.profile.name)} record capture</span></div>`:''}<p class="row-sub">Collector activity: ${esc(o.observability?.collector?.status||'unavailable')}; liveness: ${esc(o.observability?.collector?.liveness||'unknown')}. Capture: ${esc(o.observability?.status||'unavailable')}. Wiki: ${esc(o.observability?.consumer_health?.wiki?.status||'unavailable')}. Artifacts: ${esc(o.observability?.consumer_health?.artifacts?.status||'unavailable')}. Backup: ${esc(o.observability?.consumer_health?.backup?.status||'unavailable')}.</p><p class="row-sub">${esc(o.capture?.profile?.reason||'Session coverage is shown with each captured conversation.')}</p>${o.capture?.errors?.length?`<p class="row-sub">${o.capture.errors.length} recent recorded capture errors. ${link('activity','Inspect history',{kind:'all',q:'failed'})}</p>`:''}</div>`)}${panel('Latest reports',docs.items.map(docMini).join('')||empty('No reports yet','Reports and sealed proofs will appear here.'),link('library','Library'))}
</div></div>`);}
function taskRows(tasks){return tasks.map(t=>`<tr><td><span class="mono">${String(t.number||Number(t.id.replace(/\D/g,''))).padStart(2,'0')}</span></td><td><button class="row-title" data-task="${esc(t.id)}">${esc(t.title)}</button><span class="row-sub"><span class="mono">${esc(t.id)}</span> / ${esc(t.op||'Unassigned operation')}</span></td><td>${badge(t.status)}</td><td><span class="row-sub">${esc(short(t.report?.result||t.report?.what||(t.status==='done'?'Work summary not recorded':'Work not yet recorded complete'),150))}</span></td><td><span class="row-sub">${esc(date(t.completed_at))}</span>${t.completed_session?link('sessions',short(t.completed_session,21),{sid:t.completed_session}):'<small class="muted">Session not recorded</small>'}</td><td>${t.proof?`<a href="${esc(href('library',{path:proofPath(t.proof)}))}">Proof ${icon('external')}</a>`:'<span class="muted">No proof linked</span>'}</td></tr>`).join('');}
function outcomeRows(items){return items.map(x=>`<tr><td><span class="task-number">${String(x.number||Number(x.id.replace(/\D/g,''))).padStart(2,'0')}</span></td><td><button class="row-title" data-outcome="${esc(x.id)}">${esc(x.title)}</button><span class="row-sub">${esc(x.id)} / ${esc(stageName(x.stage))}</span></td><td>${badge(x.status)}</td><td>${badge(x.recorded_status)}<span class="row-sub">${esc(date(x.recorded_completed_at))}</span>${x.recorded_completed_session?link('sessions',short(x.recorded_completed_session,20),{sid:x.recorded_completed_session}):''}</td><td><span class="row-sub">${esc(short(x.reason||'Open for method, result and proof',140))}</span></td></tr>`).join('');}
async function work(ticket){
 const o=await loadOverview();if(ticket!==state.ticket)return;const p=state.params,tab=p.get('tab')||'tasks',q=(p.get('q')||'').toLowerCase(),status=p.get('status')||'',op=p.get('op')||'',stage=p.get('stage')||'',layout=p.get('layout')||'timeline';
 const scope=(tab==='outcomes'?o.items:o.tasks).filter(t=>(!op||t.op===op)&&(!stage||t.stage===stage));
 const items=scope.filter(t=>(!q||JSON.stringify(t).toLowerCase().includes(q))&&(!status||String(t.status).toLowerCase()===status));
 const visuals=`<div class="page-visuals">${segmented(scope,'status',{label:tab==='outcomes'?'Current outcome checks':'Task completion',route:'work',params:{tab,...(op?{op}:{}),...(stage?{stage}:{})}})}${tab==='outcomes'?segmented(scope,'recorded_status',{label:'Last recorded outcome results'}):dayChart(scope.filter(t=>t.status==='done'),{field:'completed_at',label:'Recorded completions',subtitle:'Dated task completions in this operation scope'})}</div>`;
 const filters=`<div class="toolbar">${search('Search work, method, result or identifier...',p.get('q'))}${select('status',[['','All statuses'],...Array.from(new Set(scope.map(t=>String(t.status).toLowerCase()))).sort().map(s=>[s,human(s)])],status,'Filter status')}${select('op',[['','All operations'],...o.ops.map(x=>[x.id,`${x.id} / ${short(x.title,35)}`])],op,'Filter operation')}${stage?`<button class="button" data-clear="stage">${esc(stageName(stage))} ${icon('close')}</button>`:''}<div class="work-view-toggle">${(tab==='tasks'?[['timeline','Timeline'],['cards','Cards'],['table','Table']]:[['timeline','Timeline'],['table','Table']]).map(([v,t])=>`<a class="${layout===v?'active':''}" href="${esc(href('work',{...Object.fromEntries(p),layout:v}))}">${t}</a>`).join('')}</div><span class="toolbar-end">${items.length} ${tab==='outcomes'?'outcomes':'tasks'}</span></div>`;
 const body=!items.length?empty('No matching work','Change the search or filters to see other work items.','work'):layout==='timeline'?renderWorkTimeline(items,tab):tab==='tasks'&&layout==='cards'?renderWorkCards(items):`<div class="panel table-wrap"><table class="data-table"><thead><tr>${(tab==='outcomes'?['No.','Outcome','Current check','Recorded completion','What needs attention']:['No.','Work item','State','What was delivered','Completed / session','Evidence']).map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${tab==='outcomes'?outcomeRows(items):taskRows(items)}</tbody></table></div>`;
 mount(heading('Work & evidence','A numbered checklist of work, methods, results and proof.',link('library','Read reports',{},'button'))+`<div class="tabs"><a class="tab ${tab==='tasks'?'active':''}" href="#work?tab=tasks">Tasks <span class="muted">${o.tasks.length}</span></a>${o.items.length||tab==='outcomes'?`<a class="tab ${tab==='outcomes'?'active':''}" href="#work?tab=outcomes">Runbook outcomes <span class="muted">${o.items.length}</span></a>`:''}</div>`+visuals+filters+(tab==='outcomes'?'<p class="route-hint">Current evidence and historical completion are separate. Open a numbered outcome for its source, method, result and completing session.</p>':'')+body);
}
function proofPath(value){if(typeof value==='object')value=value.path||value.ref||'';return String(value||'').replace(/^local:/,'');}
function evidenceLinks(values){if(!values?.length)return '<p class="muted">No evidence reference is recorded.</p>';return values.map(v=>{const path=proofPath(v);const receipt=profileOn('runs')&&path.match(/\/(?:receipts|logs)\/([a-f0-9]{32})\.(?:json|log)$/);if(receipt)return `<a class="proof-link" href="${esc(href('runs',{receipt:receipt[1]}))}">${icon('runs')}<span>Open receipt ${esc(receipt[1].slice(0,12))} and captured output</span>${icon('arrow')}</a>`;const readable=/\.(md|html?|txt|log|json|csv)$/i.test(path);return readable?`<a class="proof-link" href="${esc(href('library',{path}))}">${icon('file')}<span>${esc(path)}</span>${icon('external')}</a>`:`<div class="proof-link">${icon('file')}<span>${esc(path)}</span></div>`;}).join('');}
function showInspector(title,html,label='WORK RECORD',reader=false){$('#inspector').classList.toggle('reader',reader);$('#inspector-label').textContent=label;$('#inspector-content').innerHTML=`<h2 id="inspector-title" class="detail-title">${esc(title)}</h2>${html}`;hydrate($('#inspector'));if(!$('#inspector').open)$('#inspector').showModal();}
function taskContract(t){const c=t.contract;const cmd=`bin/alpaca task contract ${t.id} --input "..." --expected "..." --done-bar "..." --fail-case "..."`;if(!c)return `<section class="detail-section"><h3>Contract</h3><p class="inline-warning">No input, expected output, done bar or fail case is recorded for this task yet.</p><code class="ct-cmd">${esc(cmd)}</code></section>`;const card=(n,title,list,cls='')=>`<section class="ct-card ${cls}"><h3><span class="ct-n">${n}</span>${title}</h3>${list.length?`<ul class="ct-list">${list.map(x=>`<li><b>&middot;</b><div>${esc(x)}</div></li>`).join('')}</ul>`:'<p class="ct-note">Not stated.</p>'}</section>`;const st=c.stage&&(state.overview.stages||[]).find(s=>s.stage===c.stage);return `<section class="detail-section"><h3>Contract</h3><div class="ct"><div class="ct-head"><strong>${esc(t.id)}</strong><span>recorded ${esc(date(c.at))} by ${esc(c.by||'unknown')}${c.source?' &middot; from '+esc(c.source):''}</span>${c.stage?`<span>stage <b>${esc(stageName(c.stage))}</b>${st?.receipt_id?(profileOn('runs')?` &middot; <a class="text-link" href="${esc(href('runs',{receipt:st.receipt_id}))}">latest run contract ${badge(st.status)}</a>`:` &middot; latest run ${badge(st.status)}`):' &middot; no run yet'}</span>`:''}</div><div class="ct-grid ct-grid-task">${card(1,'Input',c.input||[])}${card(2,'Expected output',c.expected||[])}${card(3,'Done bar',c.done_bar||[])}${card(4,'Fail cases',c.fail_cases||[])}</div></div></section>`;}
function inspectTask(id){
 const t=state.overview.tasks.find(t=>t.id===id);if(!t)return;const op=state.overview.ops.find(x=>x.id===t.op),r=t.report;
 const paragraph=(title,body,cls='')=>`<section class="detail-section ${cls}"><h3>${title}</h3><div class="record-prose markdown">${markdown(body||'Not recorded.',r?.path||'')}</div></section>`;
 showInspector(`${String(t.number||Number(t.id.replace(/\D/g,''))).padStart(2,'0')}. ${t.title}`,`<dl class="detail-grid"><dt>Task</dt><dd class="mono">${esc(t.id)}</dd><dt>State</dt><dd>${badge(t.status)}</dd>${t.description?`<dt>Full statement</dt><dd>${esc(t.description)}</dd>`:''}<dt>Operation</dt><dd>${esc(op?.title||t.op)}</dd><dt>Created</dt><dd>${esc(date(t.created_at))}</dd><dt>Last updated</dt><dd>${esc(date(t.updated_at))}</dd><dt>Completed</dt><dd>${esc(date(t.completed_at))}</dd><dt>Completing session</dt><dd>${t.completed_session?link('sessions',t.completed_session,{sid:t.completed_session}):'Not recorded'}</dd><dt>Assigned worker</dt><dd>${esc(t.claimant||'Unassigned')}</dd><dt>Assigned session</dt><dd>${t.assigned_session?link('sessions',t.assigned_session,{sid:t.assigned_session}):'Not recorded'}</dd></dl>${taskContract(t)}${paragraph('Purpose and source',t.purpose||t.reason||op?.done_when)}${t.source?paragraph('Recorded source reference',t.source):''}${t.status!=='done'&&t.last_completion?'<p class="inline-warning">This task was reopened. The linked report describes earlier work; it does not establish a new completion.</p>':''}${paragraph('What was done',r?.what)}${paragraph('How it was done',r?.how,'record-method')}${paragraph('Result',r?.result)}${r?.truncated?'<p class="inline-warning">These are bounded report excerpts. Read the full report for the complete method and result.</p>':''}<section class="detail-section"><h3>Work report and proof</h3>${evidenceLinks(t.proof?[t.proof]:[])}${r?.sealed?`<p class="row-sub">Seal recorded ${esc(date(r.sealed_at))}. Current proof verification has not been run by this view.</p>`:''}</section>${t.history?.length?`<section class="detail-section"><h3>Work history</h3><ol class="record-lifecycle">${t.history.map(e=>`<li><time>${esc(date(e.at))}</time><span>${esc(e.to?'Moved to '+human(e.to):human(e.kind))}${e.session?`<br>${link('sessions',short(e.session,34),{sid:e.session})}`:''}</span></li>`).join('')}</ol></section>`:''}<div class="link-row">${link('activity','Task history',{ref:t.id})}${link('messages','Related messages',{q:t.id})}</div>`);
}
function inspectOutcome(id){
 const t=state.overview.items.find(x=>x.id===id);if(!t)return;
 showInspector(`${String(t.number||Number(t.id.replace(/\D/g,''))).padStart(2,'0')}. ${t.title}`,`<dl class="detail-grid"><dt>Outcome</dt><dd class="mono">${esc(t.id)}</dd><dt>Current check</dt><dd>${badge(t.status)}</dd>${t.description?`<dt>Full statement</dt><dd>${esc(t.description)}</dd>`:''}<dt>Recorded result</dt><dd>${badge(t.recorded_status)}</dd><dt>Stage</dt><dd>${esc(stageName(t.stage))}</dd><dt>Current check time</dt><dd>${esc(date(t.verified_at))}</dd><dt>Recorded completion</dt><dd>${esc(date(t.recorded_completed_at))}</dd><dt>Completing session</dt><dd>${t.recorded_completed_session?link('sessions',t.recorded_completed_session,{sid:t.recorded_completed_session}):'Not recorded'}</dd></dl><section class="detail-section"><h3>What the check found</h3><p>${esc(t.reason||'No explanation was recorded.')}</p></section><section class="detail-section record-method"><h3>Recorded verification method</h3><p>${esc(t.method?.description||t.method?.oracle||'Method not recorded.')}</p>${t.method?.proof_kind?`<p class="row-sub">Evidence kind: ${esc(t.method.proof_kind)}</p>`:''}</section>${t.observed?`<section class="detail-section"><h3>Observed result</h3><pre class="raw-data">${esc(typeof t.observed==='string'?t.observed:JSON.stringify(t.observed,null,2))}</pre></section>`:''}<section class="detail-section"><h3>Evidence</h3>${evidenceLinks(t.evidence)}</section><section class="detail-section"><h3>Runbook source</h3>${evidenceLinks(typeof t.source==='string'?[t.source]:[])}${typeof t.source!=='string'?`<p>${esc(JSON.stringify(t.source||{}))}</p>`:''}</section><div class="link-row">${profileOn('runs')?link('runs','Open run history'):''}${link('activity','Outcome history',{ref:t.ref||t.id})}</div>`);
}
async function activity(ticket,more=false){const p=state.params;const data=await api('/hub/history.json',{q:p.get('q'),kind:p.get('kind')||'work',session:p.get('session'),ref:p.get('ref'),before:more?state.history?.next_before:null});if(ticket!==state.ticket)return;state.history=more?{...data,items:[...state.history.items,...data.items]}:data;const h=state.history;mount(heading('Activity','A complete, searchable history of the project record. Open an event to inspect its original context.')+`<div class="page-visuals">${dayChart(h.items,{label:'Activity by day',subtitle:'Loaded '+h.items.length+' of '+h.total+' matching records'})}${categoryBars(h.items,'kind','Loaded event types')}</div><div class="toolbar">${search('Search the recorded history...',p.get('q'))}${select('kind',[['progress','Task and run progress'],['work','Work and checks'],['all','All recorded events'],['msg','Messages'],['task-move','Task transitions'],['session-start','Session starts']],p.get('kind')||'work','Filter events')}${p.get('session')?`<button class="button" data-clear="session">Session filter ${icon('close')}</button>`:''}${p.get('ref')?`<button class="button" data-clear="ref">${esc(p.get('ref'))} ${icon('close')}</button>`:''}<span class="toolbar-end">${count(h.items.length)} shown / ${count(h.total)} matching events</span></div><section class="panel timeline">${h.items.length?eventRows(h.items,true):empty('No matching events','Try another term or switch to all recorded events.','activity')}${h.has_more?'<div class="pagination"><button class="button" data-action="history-more">Load earlier events</button></div>':'<div class="panel-foot">Beginning of the matching record.</div>'}</section>`);}
async function messages(ticket){const o=await loadOverview();if(ticket!==state.ticket)return;const p=state.params;const q=(p.get('q')||'').toLowerCase(),kind=p.get('kind')||'',to=p.get('to')||'';const list=o.messages.filter(m=>(!q||JSON.stringify(m).toLowerCase().includes(q))&&(!kind||m.kind===kind)&&(!to||m.to===to));mount(heading('Messages','Reports, decisions, and handoffs left in the shared record for people and agents.')+collectionVisuals(list,'kind','Message types in the filtered record')+`<div class="toolbar">${search('Search messages or task references...',p.get('q'))}${select('kind',[['','All message types'],...Array.from(new Set(o.messages.map(m=>m.kind))).sort().map(k=>[k,human(k)])],kind,'Message type')}${select('to',[['','All recipients'],...Array.from(new Set(o.messages.map(m=>m.to).filter(Boolean))).sort().map(k=>[k,k])],to,'Recipient')}<span class="toolbar-end">${list.length} messages</span></div>${list.map(m=>`<article class="message-card"><div class="message-header"><span class="avatar">${esc((m.sender||m.session||'A').slice(0,2).toUpperCase())}</span><strong>${esc(m.sender||short(m.session,30)||'Agent')}</strong><span>to ${esc(m.to||'workspace')}</span>${badge(m.kind)}<time>${esc(date(m.ts))}</time></div><div class="message-body-preview">${esc(short(m.body,650))}</div>${String(m.body||'').length>650?`<details class="message-expand"><summary>Read full message</summary><div class="message-body">${esc(m.body)}</div></details>`:''}<div class="message-footer">${m.ref?link('activity',m.ref,{ref:m.ref}):''}${m.session?link('sessions','Open session',{sid:m.session}):''}</div></article>`).join('')||empty('No matching messages','Agent reports and handoffs appear here when they are recorded.','messages')}`);}
async function library(ticket,more=false){const p=state.params;const seen=flags.seen('library');const data=await api('/hub/documents.json',{q:p.get('q'),category:p.get('category')||'reports',ext:p.get('ext'),offset:more?state.documents?.next_offset:0});if(ticket!==state.ticket)return;flags.settle('library',seen);state.documents=more?{...data,items:[...state.documents.items,...data.items]}:data;const d=state.documents;mount(heading('Library','Reports and project knowledge, organized for reading. Tool documentation is available when you need it.')+collectionVisuals(d.items,'ext','Formats in '+d.items.length+' loaded documents / '+d.total+' matching documents')+`<div class="toolbar">${search('Search reports, titles, or paths...',p.get('q'))}${select('category',[['reports','Reports & knowledge'],['proofs','Sealed work & proof'],['runbooks','Runbooks'],['decisions','Decisions & plans'],['tools','Tool documentation'],['all','All documents']],p.get('category')||'reports','Document collection')}${select('ext',[['','All formats'],['md','Markdown'],['html','HTML']],p.get('ext')||'','Document format')}<span class="toolbar-end">${count(d.total)} documents</span></div><div class="panel table-wrap">${d.items.length?`<table class="data-table"><thead><tr><th>Document</th><th>Collection</th><th>Format</th><th>Updated</th></tr></thead><tbody>${d.items.map(doc=>`<tr><td><a class="row-title" href="${esc(href('library',{...Object.fromEntries(p),path:doc.path}))}">${esc(doc.title)}</a><span class="row-sub">${esc(short(doc.path,110))}${doc.task?` &middot; ${esc(doc.task)}`:''}</span></td><td>${badge(doc.sealed?'Sealed proof':doc.category)}</td><td><span class="mono">${esc(doc.ext.toUpperCase())}</span></td><td><span class="row-sub">${esc(date(doc.mtime))}</span></td></tr>`).join('')}</tbody></table>`:empty('No documents match','Change the collection or search to find a report.')} ${d.has_more?'<div class="pagination"><button class="button" data-action="documents-more">Load more documents</button></div>':''}</div>`);if(p.get('path'))await readDocument(p.get('path'),ticket);}
// Markdown is rendered from escaped text only. Raw HTML never enters the parent document.
function inline(text,basePath=""){let v=esc(text);const codes=[];v=v.replace(/`([^`]+)`/g,(_,s)=>{codes.push(`<code>${s}</code>`);return `\u0001${codes.length-1}\u0001`;});v=v.replace(/\[([^\]]+)\]\(([^\s)]+)\)/g,(_,label,target)=>{const raw=target.replace(/&amp;/g,'&');if(/^https?:\/\//i.test(raw))return `<a href="${target}" target="_blank" rel="noopener noreferrer">${label}</a>`;if(/^(?:javascript|data|vbscript):/i.test(raw))return label;try{const local=raw.replace(/^local:/,'');const resolved=new URL(local,'https://hub.invalid/'+basePath);if(resolved.origin==='https://hub.invalid'&&/\.(md|html?)$/i.test(resolved.pathname))return `<a href="${esc(href('library',{path:decodeURIComponent(resolved.pathname).replace(/^\//,'')}))}">${label}</a>`;}catch{}return `<span>${label} <code>${target}</code></span>`;});v=v.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return v.replace(/\u0001(\d+)\u0001/g,(_,n)=>codes[Number(n)]);}
function markdown(text,basePath=""){const fmt=t=>inline(t,basePath);const lines=String(text).split('\n');let out='',para=[],code=null,list=null;const flush=()=>{if(para.length){out+=`<p>${para.map(fmt).join('<br>')}</p>`;para=[];}if(list){out+=`</${list}>`;list=null;}};for(let i=0;i<lines.length;i++){const line=lines[i];if(/^\s*```/.test(line)){flush();if(code!==null){out+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;code=null;}else code=[];continue;}if(code!==null){code.push(line);continue;}if(i+1<lines.length&&line.includes('|')&&/^\s*\|?\s*:?-{3,}/.test(lines[i+1])){flush();const cells=s=>s.trim().replace(/^\||\|$/g,'').split('|').map(v=>v.trim());out+='<table><thead><tr>'+cells(line).map(v=>`<th>${fmt(v)}</th>`).join('')+'</tr></thead><tbody>';i+=2;for(;i<lines.length&&lines[i].includes('|')&&lines[i].trim();i++)out+='<tr>'+cells(lines[i]).map(v=>`<td>${fmt(v)}</td>`).join('')+'</tr>';out+='</tbody></table>';i--;continue;}const h=line.match(/^(#{1,6})\s+(.+)/);if(h){flush();out+=`<h${h[1].length}>${fmt(h[2])}</h${h[1].length}>`;continue;}if(/^\s*([-*_])\1\1+\s*$/.test(line)){flush();out+='<hr>';continue;}const li=line.match(/^\s*(?:([-*+])|\d+\.)\s+(.+)/);if(li){if(para.length){out+=`<p>${para.map(fmt).join('<br>')}</p>`;para=[];}const tag=li[1]?'ul':'ol';if(list!==tag){if(list)out+=`</${list}>`;out+=`<${tag}>`;list=tag;}out+=`<li>${fmt(li[2]).replace(/^\[x\]/i,'&#9745;').replace(/^\[ \]/,'&#9744;')}</li>`;continue;}if(line.startsWith('>')){flush();out+=`<blockquote>${fmt(line.replace(/^>\s?/,''))}</blockquote>`;continue;}if(!line.trim()){flush();continue;}if(list){out+=`</${list}>`;list=null;}para.push(line);}flush();if(code!==null)out+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;return out;}
async function readDocument(path,ticket=state.ticket){showInspector(path,'<div class="loading"><span class="spinner"></span>Opening document...</div>','DOCUMENT',true);try{const d=await api(/\.(md|html?)$/i.test(path)?'/hub/document.json':'/files/read',{path});if(ticket!==state.ticket)return;if(d.error)throw Error(d.error);const html=/\.html?$/i.test(path);const doc=state.documents?.items.find(x=>x.path===path);showInspector(doc?.title||path.split('/').pop(),`<div class="reader-controls"><span class="reader-path">${esc(path)}</span>${badge(html?'HTML':'Markdown')}<button class="button" data-action="download-document">${icon('download')}Save copy</button></div>${d.truncated?'<div class="notice"><div><h3>This document is partially displayed</h3><p>The reader reached the server limit. The full source remains in the project.</p></div></div>':''}${html?'<iframe class="report-frame" sandbox="" referrerpolicy="no-referrer" title="Report preview"></iframe>':`<article class="markdown">${markdown(d.text,path)}</article>`}`,'DOCUMENT',true);state.document=d;if(html){const parsed=new DOMParser().parseFromString(d.text,'text/html');parsed.querySelectorAll('script,base,meta[http-equiv],iframe,object,embed,form').forEach(e=>e.remove());const csp=parsed.createElement('meta');csp.httpEquiv='Content-Security-Policy';csp.content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src data:; form-action 'none'; base-uri 'none'";parsed.head.prepend(csp);$('#inspector iframe').srcdoc='<!doctype html>'+parsed.documentElement.outerHTML;}}catch(e){$('#inspector-content').innerHTML=`<h2 id="inspector-title" class="detail-title">Document unavailable</h2><p class="reader-path">${esc(path)}</p><div class="detail-section">${errorView(e)}</div>`;}}
async function runs(ticket){const [data,o]=await Promise.all([loadRuns(),loadOverview()]);if(ticket!==state.ticket)return;const p=state.params,q=(p.get('q')||'').toLowerCase(),status=p.get('status')||'';const rows=data.items.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!status||String(r.verdict).toLowerCase()===status));const selected=rows.find(r=>r.id===p.get('run')||(p.get('receipt')&&(r.receipt_id===p.get('receipt')||r.stages?.some(s=>s.receipt_id===p.get('receipt')))));mount(heading('Runs & logs','Follow execution from recorded attempts to stage results and the original output.',link('work','Check current evidence',{tab:'outcomes'},'button'))+`<div class="toolbar">${search('Search design, stage, result, or run...',p.get('q'))}${select('status',[['','All results'],...Array.from(new Set(data.items.map(r=>String(r.verdict).toLowerCase()))).map(v=>[v,human(v)])],status,'Run result')}<span class="toolbar-end">${rows.length} recorded runs</span></div><p class="route-hint">Run results describe what happened at the time. Current acceptance is checked separately against today's inputs and evidence.</p>${selected?runDetail(selected,p.get('receipt')):(o.active_jobs?.length?`<a class="lv-banner" href="#live"><i class="lv-pulse"></i><strong>${o.active_jobs.length} job${o.active_jobs.length===1?'':'s'} running now</strong><span>Open live logs</span>${icon('arrow')}</a>`:'')+runsOverview(rows,stageName,o.profile?.stages||[])+runVisuals(rows,null)}<div class="panel table-wrap">${rows.length?`<table class="data-table"><thead><tr><th>Run / design</th><th>Stage</th><th>Result</th><th>Started</th><th>Duration</th></tr></thead><tbody>${rows.map(r=>`<tr><td><a class="row-title" href="${esc(href('runs',{run:r.id}))}">${esc(r.design||'Unspecified design')}</a><span class="row-sub mono">${esc(short(r.id,24))}</span></td><td>${esc(stageName(r.stage))}<span class="row-sub">${r.stages?.length||1} recorded stage${r.stages?.length===1?'':'s'}</span></td><td>${badge(r.verdict)}</td><td><span class="row-sub">${esc(date(r.started_at))}</span></td><td><span class="row-sub">${esc(duration(r.elapsed_s))}</span></td></tr>`).join('')}</tbody></table>`:empty('No runs match','Run receipts will appear here as stages are executed.','runs')}</div>${data.errors?.length?`<p class="inline-warning">${data.errors.length} run records could not be fully read.</p>`:''}`);if(selected){const stages=selected.stages||[];const s=stages.find(s=>s.receipt_id===p.get('receipt'))||stages.at(-1);const receipt=s?.receipt_id||selected.receipt_id;if(receipt){const live=String(s?.verdict||selected.verdict).toUpperCase()==='RUNNING';state.log={receipt,text:'',offset:0,base:1,following:live,flagged:false,query:'',run:selected,active:s,scan:null,scanSize:-1,jump:+p.get('line')||0};loadReview(state.log);loadContract(state.log);await fetchLog(true);state.timer=setInterval(()=>{if(state.log?.following)fetchLog();},2500);}}}
function runDetail(r,receipt){const s=(r.stages||[]).find(x=>x.receipt_id===receipt)||(r.stages||[]).at(-1);return runDashboard(r,s,stageName,{session:r.session?link('sessions','Session behind this run',{sid:r.session}):'',evidence:`<details class="detail-section"><summary>Evidence references</summary>${evidenceLinks(r.evidence)}</details><div id="resources" class="resource-line"></div>`});}
let liveCtl=null;
function stopLive(){if(liveCtl){liveCtl.stop();liveCtl=null;}}
async function live(ticket){stopLive();const pinned=(state.params.get('jobs')||'').split(',').filter(j=>/^[a-f0-9]{32}$/.test(j));const ctl=createLive({api,stageName});liveCtl=ctl;const timer=await ctl.start(pinned);if(ticket!==state.ticket||liveCtl!==ctl){clearInterval(timer);ctl.stop();return;}state.timer=timer;}
let logBusy=false;
const LOG_CAP=8*1024*1024;
async function fetchLog(all=false){const l=state.log;if(!l||logBusy)return;logBusy=true;try{do{const d=await api('/hub/log.json',{receipt:l.receipt,offset:l.offset});if(state.log!==l)return;if(d.offset<l.offset){l.text='';l.base=1;}l.text+=d.text;l.offset=d.offset;l.has_more=d.has_more;l.size=d.size;}while(all&&l.has_more&&l.text.length<LOG_CAP);if(l.text.length>LOG_CAP){const cut=l.text.indexOf('\n',l.text.length-LOG_CAP)+1;l.base+=(l.text.slice(0,cut).match(/\n/g)||[]).length;l.text=l.text.slice(cut);l.trimmed=true;}renderLog();if(l.size!==l.scanSize&&(!l.scanAt||Date.now()-l.scanAt>8000))await loadScan(l);}catch(e){if(state.log===l&&$('#log-output')){$('#log-output').textContent=e.message;$('#log-status').textContent='No captured output is available for this receipt.';}}finally{logBusy=false;}}
async function loadContract(l){try{const c=await api('/hub/contract.json',{receipt:l.receipt});if(state.log===l)renderContract(c,l.receipt);}catch(e){if(state.log===l)renderContract({error:e.message});}}
async function loadReview(l){try{const data=await api('/hub/logreview.json',{receipt:l.receipt});if(state.log!==l)return;l.reviewLines=reviewLines(data);renderReview(data,l.receipt);renderLog();}catch(e){if(state.log===l&&$('#rl-review'))$('#rl-review').innerHTML=`<p class="inline-warning">Agent reviews could not be read: ${esc(e.message)}</p>`;}}
async function loadScan(l){l.scanAt=Date.now();try{const scan=await api('/hub/logscan.json',{receipt:l.receipt});if(state.log!==l)return;l.scan=scan;l.scanSize=scan.size;renderScan(scan,l.run,l.active);renderLog();const first=l.jump||(!l.following&&scan.first_error?.line);if(first&&!l.jumped){l.jumped=true;jumpToLine(l,first);}}catch(e){if(state.log===l&&$('#rl-kpis'))$('#rl-kpis').innerHTML=`<div class="rl-kpi tone-attention"><span>Log scan</span><strong>Unavailable</strong><small>${esc(e.message)}</small></div>`;}}
function renderLog(){renderLogLines(state.log);}
function saveText(text,name){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function sessions(ticket,automatic=false){
 const p=state.params,sid=p.get('sid'),view=p.get('view')||'analysis',key=location.hash;
 // A live refresh patches the view already on screen instead of rebuilding it. The conversation
 // tab is being read: it keeps its content and the "New activity available" refresh button.
 if(automatic&&sid&&view==='conversation')return false;
 const inPlace=Boolean(automatic&&state.sessionsKey===key&&$(sid?'#session-detail':'#analytics-index'));
 // A failed list fetch goes to route(): a quiet refresh keeps the page and retries later.
 const seen=flags.seen('analytics'),data=await loadSessions();if(ticket!==state.ticket)return;
 const rows=(data.sessions||[]).filter(s=>s.class==='work'||!s.class),q=(p.get('q')||'').toLowerCase();
 const selected=rows.find(s=>s.sid===sid)||(sid?{sid,title:sid}:null);
 const bar=sid?'analysis-session-controls':'toolbar',controls=sid?`${link('sessions','All sessions')}<select class="filter-select" data-session-switch aria-label="Choose a session">${rows.map(s=>`<option data-key="${esc(s.sid)}" value="${esc(s.sid)}" ${sid===s.sid?'selected':''}>${esc(short(s.title||s.sid,95))}</option>`).join('')}</select><span class="toolbar-end">${rows.length} working sessions / probes excluded</span>`:`${search('Search session title or identifier...',p.get('q'))}<span class="toolbar-end">${rows.length} working sessions / probes excluded</span>`;
 if(inPlace)patchHtml($(`#main .${bar}`),controls);
 else{mount(heading('Session analytics','Understand the cost, context and actions behind the work.',link('library','Browse reports',{},'button'),'ENGINEERING INSIGHT')+`<div class="${bar}">${controls}</div>`+`<div class="${sid?'session-analytics-layout':'analysis-index'}"><div ${sid?'class="panel" id="session-detail"':'id="analytics-index"'}><div class="loading"><span class="spinner"></span>Reading usage and conversation sources...</div></div></div>`);state.sessionsKey=key;}
 // The switcher names the open session whatever the patch did to the option list.
 const switcher=$('#main [data-session-switch]');if(switcher&&[...switcher.options].some(o=>o.value===sid))switcher.value=sid;
 try{
  if(!sid){const index=await api('/hub/analytics-index.json');if(ticket!==state.ticket)return;const filtered={...index,sessions:index.sessions.filter(s=>!q||JSON.stringify([s.title,s.sid,s.operator]).toLowerCase().includes(q))};(inPlace?patchHtml:renderHtml)($('#analytics-index'),analyticsIndex(filtered));flags.settle('analytics',seen);return;}
  const [d,a,family]=await Promise.all([api('/hub/session.json',{sid,child:p.get('child'),around:view==='conversation'?p.get('around'):null}),api('/hub/analytics.json',{sid,child:p.get('child')}),view==='crew'?api('/hub/analytics-children.json',{sid}):null]);
  if(ticket!==state.ticket)return;state.detail=d;state.analytics=a;state.family=family;if(inPlace)patchHtml($('#session-detail'),sessionDetailHtml(d,selected,true));else renderSessionDetail(d,selected);flags.settle('analytics',seen);
 }catch(e){if(ticket!==state.ticket)return;if(inPlace)throw e;$(sid?'#session-detail':'#analytics-index').innerHTML=sid&&e.status===404?`<div class="panel-body">${empty('No captured session is registered','The work record names '+sid+', but no session or conversation source is available for that identifier. Completion provenance remains in the task history.','sessions')}<div class="link-row">${link('activity','Read recorded activity',{session:sid})}${link('work','Back to work and evidence')}</div></div>`:errorView(e);}
}
function renderSessionDetail(d,summary){renderHtml($('#session-detail'),sessionDetailHtml(d,summary));}
// keepLedger: a live patch of the same tab keeps the response-ledger search, filters and page.
function sessionDetailHtml(d,summary,keepLedger=false){
 const p=state.params,tab=p.get('view')||'analysis',sid=d.session.sid,child=p.get('child'),coverage=d.coverage,children=d.children||[],a=state.analytics;
 const tabs=[['analysis','Overview'],['cost','Costs & tokens'],['context','Context window'],['actions','Actions & hooks'],['crew','Agent crew'],['conversation','Conversation & tools'],['report','Work & reports']];
 let content;
 if(['analysis','cost','context','actions'].includes(tab)){content=renderAnalytics(a,tab,{keepLedger});}
 else if(tab==='crew'){content=renderCrew(state.family);}
 else if(tab==='report'){
  const tasks=(state.overview?.tasks||[]).filter(t=>t.assigned_session===sid||t.completed_session===sid||t.history?.some(e=>e.session===sid)),msgs=(state.overview?.messages||[]).filter(m=>m.session===sid);
  content=`<div class="conversation"><section class="detail-section"><h3>Recorded work</h3>${tasks.length?`<div class="table-wrap"><table class="data-table"><tbody>${taskRows(tasks)}</tbody></table></div>`:'<p class="muted">No task assignment, completion or lifecycle event is recorded for this session.</p>'}</section><section class="detail-section"><h3>Reports and handoffs</h3>${msgs.length?msgs.map(m=>`<article class="message-card"><div class="message-header">${badge(m.kind)}${esc(date(m.ts))}</div><p class="message-body">${esc(m.body)}</p></article>`).join(''):'<p class="muted">No session messages are recorded.</p>'}</section>${link('activity','Full session work history',{session:sid})}</div>`;
 }else{
  content=`<div class="conversation">${p.has('around')?`<div class="conversation-focus">Opened around transcript line ${esc(p.get('around'))}. Usage is measured per model response; a response can contain multiple visible blocks. <a href="${esc(href('sessions',{sid,...(child?{child}:{}),view:'cost'}))}">Back to costs and tokens</a></div>`:''}${d.has_more?'<div class="pagination"><button class="button" data-action="session-earlier">Load earlier conversation</button></div>':''}${d.messages.length?d.messages.map(messageTurn).join(''):empty('No conversation is captured',coverage.reason||'Only the session registration is available.','messages')}${d.has_later?'<div class="pagination"><button class="button" data-action="session-later">Load later conversation</button></div>':''}<div class="capture-note">${esc(coverage.reason)} ${d.messages.length} of ${d.total}${coverage.total_is_exact?'':'+'} captured entries displayed.</div></div>`;
 }
 return `<div class="session-summary"><span class="eyebrow">${child?'CHILD AGENT':'SESSION RECORD'} / ${esc(a?.session.operator||d.session.operator)}</span><h2>${esc(child?d.session.title:summary.title||d.session.title)}</h2><span class="reader-path">${esc(sid)}</span><div class="session-statline"><div><strong>${count(a?.summary.responses)}</strong>model responses</div><div><strong>${count(a?.summary.tool_calls??d.session.tool_calls)}</strong>tool calls</div><div><strong>${count(children.length)}</strong>child records</div><div><strong>${esc(child?'Separate':duration(summary.span_s))}</strong>${child?'child scope':'captured span'}</div></div>${children.length||child?`<div class="child-links">${child?`<a href="${esc(href('sessions',{sid,view:tab}))}">Back to parent session</a>`:''}${children.length?`<details class="children-summary"><summary>Explore ${children.length} child agent records</summary><div class="child-links">${children.map(c=>`<a href="${esc(href('sessions',{sid,child:c.id,view:tab}))}">${esc(short(c.title,65))}</a>`).join('')}</div></details>`:''}</div>`:''}<div class="link-row">${link('activity','Recorded activity',{session:sid})}${link('messages','Messages',{q:sid})}</div></div><div class="tabs" style="padding:0 12px;margin-bottom:0">${tabs.map(([key,label])=>`<a class="tab ${tab===key?'active':''}" href="${esc(href('sessions',{sid,...(child?{child}:{}),view:key}))}">${label}</a>`).join('')}</div>${content}`;
}
function messageTurn(m){
 const a=state.analytics;const entry=(a?.ledger||[]).find(r=>r.message_ids?.includes(m.id)||r.source?.line===m.source?.line),around=Number(state.params.get('around'));
 const meta=entry?`${entry.usage?.input_tokens!=null?count(entry.usage.input_tokens)+' input / '+count(entry.usage.output_tokens)+' output':''}${entry.cost?.total_usd!=null?' / $'+entry.cost.total_usd.toFixed(4)+' estimated':''}`:'';
 return `<article class="turn ${around&&m.source?.line===around?'usage-focus':''}" data-source-line="${m.source?.line||''}"><div class="turn-header"><span class="role ${esc(m.role)}">${esc(human(m.role))}</span><time>${esc(date(m.ts))}</time><span class="mono">${esc(m.source?.kind||'')}${m.source?.line?' / '+m.source.line:''}</span></div>${meta?`<div class="capture-note">${esc(meta)} <a href="${esc(href('sessions',{sid:state.params.get('sid'),view:'cost',...(state.params.get('child')?{child:state.params.get('child')}:{})}))}">Response costs</a></div>`:''}${m.text?`<div class="turn-text">${esc(m.text)}</div>`:''}${m.truncated?'<p class="inline-warning">This captured entry is truncated.</p>':''}${(m.tools||[]).map(t=>`<details class="tool"><summary>${esc(t.name)} &middot; ${esc(t.status||'captured')}${t.input_truncated||t.result_truncated?' / partial capture':''}</summary><div class="panel-body"><h4>Input</h4><pre class="tool-output">${esc(typeof t.input==='string'?t.input:JSON.stringify(t.input,null,2))}</pre><h4>Result</h4><pre class="tool-output">${esc(typeof t.result==='string'?t.result:JSON.stringify(t.result,null,2)||'No result captured')}</pre></div></details>`).join('')}</article>`;
}
function changeFilter(key,value){const p=new URLSearchParams(state.params);if(value)p.set(key,value);else p.delete(key);p.delete('path');location.hash=href(state.route,Object.fromEntries(p));}
async function route(force=false,quiet=false){const focused=document.activeElement?.dataset?.filter;const caret=document.activeElement?.selectionStart;const ticket=++state.ticket;clearInterval(state.timer);state.timer=null;state.log=null;stopLive();const [rawName,query='']=location.hash.slice(1).split('?');const name=rawName==='lib'?'library':rawName|| (location.pathname.startsWith('/analytics')?'sessions':'cockpit');if(PROFILE_PAGES.includes(name)&&!state.overview){try{await loadOverview();}catch{}}state.route=visiblePages().some(p=>p[0]===name)?name:'cockpit';if(state.route!=='cockpit')document.body.classList.remove('presentation');state.params=new URLSearchParams(query);$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');if($('#inspector').open)$('#inspector').close();if($('#command').open)$('#command').close();updateChrome();document.title=`${visiblePages().find(p=>p[0]===state.route)[1]} | Alpaca`;if(!quiet)mount('<div class="loading"><span class="spinner"></span>Reading the project record...</div>');try{if(force){state.overview=null;state.runs=null;state.sessions=null;}await loadOverview();if(ticket!==state.ticket)return;updateChrome();const shown=await ({cockpit,overview,work,runs,live,activity,messages,library,sessions}[state.route])(ticket,quiet&&['cockpit','overview','sessions'].includes(state.route));if(ticket!==state.ticket)return;if(!focused&&!quiet)window.scrollTo(0,0);if(focused){const input=$(`[data-filter="${CSS.escape(focused)}"]`);if(input){input.focus();if(input.type==='search'&&caret!==null)input.setSelectionRange(caret,caret);}}if(!(quiet&&shown===false))$('#checked-at').textContent='Updated '+new Date().toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});$('#connection').classList.remove('error');$('#connection span').textContent='Connected to HTTP updates';}catch(e){if(ticket!==state.ticket)return;if(quiet)return liveFailed();mount(errorView(e));$('#connection').classList.add('error');$('#connection span').textContent='Record unavailable';}}
// A quiet refresh that fails keeps the page on screen. The connection label says so, and the caches
// the page reads are marked stale again, so the next revision or idle moment retries.
function liveFailed(){flags.mark(needs(state.route,liveParams()));$('#connection').classList.add('error');$('#connection span').textContent='Latest refresh unavailable';$('#checked-at').textContent='New activity available';$('#refresh').title='Load new activity';return false;}
let filterTimer;
document.addEventListener('input',event=>{const target=event.target;if(target.matches('input[data-filter]')){clearTimeout(filterTimer);filterTimer=setTimeout(()=>changeFilter(target.dataset.filter,target.value),450);}if(target.id==='log-search'&&state.log){state.log.query=target.value;renderLog();}if(target.id==='command-query')renderCommands(target.value);});
document.addEventListener('change',event=>{if(event.target.matches('[data-session-switch]')){location.hash=href('sessions',{sid:event.target.value});return;}if(event.target.matches('select[data-filter]'))changeFilter(event.target.dataset.filter,event.target.value);});
document.addEventListener('click',event=>{const e=event.target.closest('[data-line],[data-sev]');if(!e||!state.log||!e.closest('#main'))return;event.preventDefault();event.stopPropagation();if(e.dataset.sev&&state.log.scan)renderFindings(state.log.scan,e.dataset.sev);else if(e.dataset.line)jumpToLine(state.log,+e.dataset.line);},true);
document.addEventListener('click',async event=>{const e=event.target.closest('button,a');if(!e)return;if(e.matches('a.skip')){event.preventDefault();$('#main').focus();return;}if(e.dataset.close){$('#'+e.dataset.close).close();if(e.dataset.close==='inspector'&&state.params.has('path')){state.params.delete('path');history.replaceState(null,'',href(state.route,Object.fromEntries(state.params)));}return;}if(e.dataset.task){inspectTask(e.dataset.task);return;}if(e.dataset.outcome){inspectOutcome(e.dataset.outcome);return;}if(e.dataset.clear){changeFilter(e.dataset.clear,'');return;}const action=e.dataset.action;if(!action)return;try{if(action==='cockpit-pause'){state.cockpitPaused=!state.cockpitPaused;return cockpit(state.ticket);}if(action==='cockpit-present'){const on=document.body.classList.toggle('presentation');e.setAttribute('aria-pressed',String(on));e.querySelector('span').textContent=on?'Exit focus view':'Focus view';return;}if(action==='retry')return route(true);if(action==='history-more'){e.disabled=true;await activity(state.ticket,true);}if(action==='documents-more'){e.disabled=true;await library(state.ticket,true);}if(action==='session-earlier'){e.disabled=true;const d=state.detail;const next=await api('/hub/session.json',{sid:d.session.sid,child:state.params.get('child'),before:d.next_before});if(state.detail!==d)return;state.detail={...next,messages:[...next.messages,...d.messages],has_later:d.has_later,next_after:d.next_after};const summary=state.sessions.sessions.find(s=>s.sid===d.session.sid)||d.session;renderSessionDetail(state.detail,summary);}if(action==='session-later'){e.disabled=true;const d=state.detail;const next=await api('/hub/session.json',{sid:d.session.sid,child:state.params.get('child'),after:d.next_after});if(state.detail!==d)return;state.detail={...next,messages:[...d.messages,...next.messages],has_more:d.has_more,next_before:d.next_before};renderSessionDetail(state.detail,state.sessions.sessions.find(s=>s.sid===d.session.sid)||d.session);}if(action==='log-follow'&&state.log){state.log.following=!state.log.following;renderLog();}if(action==='log-more')await fetchLog();if(action==='log-start'&&state.log){state.log.offset=0;state.log.text='';state.log.base=1;state.log.trimmed=false;await fetchLog(true);}if(action==='log-flagged'&&state.log){state.log.flagged=!state.log.flagged;renderLog();}if(action==='log-save'&&state.log)saveText(state.log.text,state.log.receipt+'.log');if(action==='download-document'&&state.document)saveText(state.document.text,state.document.path.split('/').pop());}catch(err){e.disabled=false;toast(err.message);}});
$('#menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));});
document.addEventListener('click',e=>{if(window.innerWidth<=700&&!e.target.closest('#sidebar,#menu')){$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}});
$('#refresh').addEventListener('click',()=>route(true));
function openCommands(){renderCommands('');$('#command-query').value='';$('#command').showModal();$('#command-query').focus();}
$('#search-launch').addEventListener('click',openCommands);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands();}if(e.key==='Escape'){document.body.classList.remove('presentation');const focus=$('[data-action=cockpit-present]');if(focus){focus.setAttribute('aria-pressed','false');focus.querySelector('span').textContent='Focus view';}$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}});
function renderCommands(query){const q=query.toLowerCase();const results=visiblePages().filter(p=>p[1].toLowerCase().includes(q)).map(([id,title])=>({url:href(id),title,type:'Page',symbol:id}));if(q&&state.overview)results.push(...state.overview.tasks.filter(t=>(t.title+' '+t.id).toLowerCase().includes(q)).slice(0,8).map(t=>({url:href('work',{q:t.id}),title:t.title,type:'Work item',symbol:'work'})));if(q)results.push({url:href('library',{q:query}),title:`Search reports for "${query}"`,type:'Library',symbol:'library'},{url:href('activity',{q:query}),title:`Search history for "${query}"`,type:'Activity',symbol:'activity'});$('#command-results').innerHTML=results.map(r=>`<a class="command-result" href="${esc(r.url)}">${icon(r.symbol)}<span>${esc(r.title)}</span><small>${r.type}</small></a>`).join('');}
// Avoid scroll jumps during reading. Data changes offer a refresh; logs follow independently.
let revisions=null;
// New record data is applied on its own once the reader is idle: no open panel, no focused field.
let liveTimer=null;
function applyLive(){clearTimeout(liveTimer);liveTimer=setTimeout(()=>{if(!autoRefresh(state.route,flags.dirty,liveParams()))return;if(document.hidden||state.log||state.route==='live'||(state.route==='cockpit'&&state.cockpitPaused)||document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const ticket=state.ticket+1,mounts=state.mounts;Promise.resolve(route(false,true)).then(()=>{if(state.ticket===ticket&&state.mounts!==mounts)window.scrollTo(0,state.mountY);});},1500);}
// Scroll is put back only after a full mount by this same refresh: an in-place patch keeps the layout
// (and whatever the reader scrolled to meanwhile), and a reader who navigated keeps the new page's position.
document.addEventListener('close',e=>{if(e.target.tagName==='DIALOG')applyLive();},true);
document.addEventListener('focusout',()=>applyLive());
document.addEventListener('visibilitychange',()=>{if(!document.hidden)applyLive();});
try{const stream=new EventSource('/events');stream.addEventListener('rev',e=>{if(revisions!==null&&revisions!==e.data){const marked=changedFlags(revisions,e.data);flags.mark(marked);if(dependsOn(state.route,marked,liveParams())){$('#checked-at').textContent='New activity available';$('#refresh').title='Load new activity';}applyLive();}revisions=e.data;});stream.onerror=()=>{$('#connection').classList.add('error');$('#connection span').textContent='Reconnecting to live updates';};stream.onopen=()=>{$('#connection').classList.remove('error');$('#connection span').textContent='Connected to HTTP updates';};}catch{}
window.addEventListener('hashchange',()=>route());
hydrate();Promise.resolve(route()).finally(dropHandoff);
$('#inspector').addEventListener('cancel',()=>{if(state.params.has('path')){state.params.delete('path');history.replaceState(null,'',href(state.route,Object.fromEntries(state.params)));}});
$('#command-results').addEventListener('click',e=>{if(e.target.closest('a'))$('#command').close();});

// Refresh the overview in place while other views remain stable for reading.
let liveOverviewBusy=false;
setInterval(async()=>{if(readerEngaged()||!['overview','cockpit'].includes(state.route)||liveOverviewBusy)return;liveOverviewBusy=true;const ticket=state.ticket;const y=window.scrollY;try{await loadOverview(true);flags.mark(['runs']);if(ticket===state.ticket){const rendered=await (state.route==='cockpit'?cockpit:overview)(ticket,true);if(rendered!==false&&ticket===state.ticket){updateChrome();window.scrollTo(0,y);$('#checked-at').textContent='Updated '+new Date().toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});}}}catch{if(ticket===state.ticket){$('#connection').classList.add('error');$('#connection span').textContent='Latest refresh unavailable';}}finally{liveOverviewBusy=false;}},15000);

// HTTP connectivity, page freshness and source coverage are independent observations.
async function refreshHealth(){try{const h=await api('/health.json');const e=$('#connection');e.classList.toggle('error',h.status!=='ok');e.querySelector('span').textContent='HTTP live; page '+(h.projection?.state||'unknown')+'; capture '+(h.observability?.status||'unavailable');}catch{const e=$('#connection');e.classList.add('error');e.querySelector('span').textContent='HTTP health unavailable';}}
refreshHealth();setInterval(refreshHealth,10000);
