"""Pinned GitHub Actions templates. Generated output is explicit and edit-safe."""
from pathlib import Path
import os
import uuid
import yaml
from .config import contained

CHECKOUT = 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262'
PYTHON = 'actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065'


def checkout(ref=None):
    options = {'fetch-depth': 0, 'persist-credentials': False}
    if ref:
        options['ref'] = ref
    return {'uses': CHECKOUT, 'with': options}


def python(version):
    return {'uses': PYTHON, 'with': {'python-version': version}}


def templates(config):
    """Both workflows only run project tests. Neither has secrets, a privileged trigger or a release step."""
    bootstrap = {'name': 'Install Alpaca dependencies', 'run': 'bash setup/bootstrap.sh --python "$(command -v python)"'}
    tests = {'name': 'Project tests', 'run': 'bin/alpaca-python -m alpaca.release.ci test'}
    matrix = {'fail-fast': False, 'matrix': {'python': ['3.10', '3.12']}}
    job = {'runs-on': 'ubuntu-latest', 'strategy': matrix,
           'steps': [checkout(), python('${{ matrix.python }}'), bootstrap, tests]}
    dev = {
        'name': 'Alpaca development tests',
        'on': {'push': {}, 'workflow_dispatch': {}},
        'permissions': {'contents': 'read'},
        'concurrency': {'group': 'alpaca-tests-${{ github.repository }}-${{ github.ref }}', 'cancel-in-progress': False},
        'jobs': {'tests': job},
    }
    public = {
        'name': 'Alpaca public tests',
        'on': {'pull_request': {'branches': [config.target_branch]}},
        'permissions': {'contents': 'read'},
        'jobs': {'tests': job},
    }
    return {key: '# Generated by alpaca release init. Review before enabling.\n' + yaml.safe_dump(value, sort_keys=False)
            for key, value in [('dev', dev), ('public', public)]}


def initialize(root, config, dev_output='.github/workflows/alpaca-dev.yml',
               public_output='.alpaca/releases/workflows/alpaca-public.yml'):
    root = Path(root).resolve()
    paths = {'dev': contained(root, dev_output), 'public': contained(root, public_output)}
    if paths['dev'] == paths['public']:
        raise ValueError('dev and public workflows need different destinations')
    contents = templates(config)
    for key, path in paths.items():
        if path.exists() and (not path.is_file() or path.read_text() != contents[key]):
            raise ValueError('refusing to overwrite an edited workflow: ' + str(path.relative_to(root)))
    for key, path in paths.items():
        if path.exists():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_name(path.name + '.' + uuid.uuid4().hex + '.tmp')
        temp.write_text(contents[key])
        os.replace(temp, path)
    return {key: str(value) for key, value in paths.items()}
